// Groupe « but » : BUT (bachelor universitaire de technologie, 3 ans en IUT) pour un profil maths + physique-chimie.
// Vérifié début octobre 2026 (Onisep, ADIUT, notes flash du SIES).
add("but", [
  { id: "but_gmp", nom: "BUT Génie mécanique et productique (GMP)", duree: "3 ans", sel: 2, selNote: "Très demandé, surtout dans les grandes villes", cout: BUT_COST, alt: .8, inge: .5,
    alias: ["BUT GMP", "GMP", "DUT GMP", "génie mécanique"],
    desc: "Conception mécanique sur ordinateur (CAO), matériaux, fabrication, organisation de la production, avec beaucoup de projets et de travaux pratiques en atelier. Cinq parcours en 2e année selon l'IUT, dont innovation pour l'industrie, management de process industriel et simulation numérique.",
    apres: "Technicien supérieur en bureau d'études, en méthodes ou en production dans les industries mécaniques, ou poursuite en master ou en école d'ingénieurs.",
    mpc: "Maths et physique-chimie sont deux des quatre spécialités conseillées par l'Onisep (avec NSI et sciences de l'ingénieur) : un des BUT les plus naturels pour ton profil. Parmi les plus demandés : candidate dans plusieurs IUT et soigne tes notes de maths et de physique.",
    w: { MECA: 1, ENER: .3, MATH: .3 }, kw: ["auto", "aero", "industrie", "robot"],
    p: { enc: .9, conc: .9, intense: .5, maths: .5, phys: .6, chim: .1, code: .2, ecrit: .2, oral: .3, vente: 0, bureau: .5, terrain: .2, indus: .7, ouvert: .6, gen: .4, integ: 0, sortie: 3 },
    src: { u: "https://www.onisep.fr/ressources/univers-formation/formations/post-bac/but-genie-mecanique-et-productique-parcours-innovation-pour-l-industrie", l: "Fiche Onisep" } },

  { id: "but_mp", nom: "BUT Mesures physiques", duree: "3 ans", sel: 1, selNote: "Demande en hausse ; très variable selon l'IUT", cout: BUT_COST, alt: .6, side: true, inge: .5,
    alias: ["Mesures physiques", "BUT MP", "DUT Mesures physiques", "instrumentation"],
    desc: "Mesurer et contrôler en laboratoire et dans l'industrie : instrumentation, capteurs, matériaux, analyses physico-chimiques, avec beaucoup de travaux pratiques. Le BUT le plus orienté physique. Trois parcours en 2e année selon l'IUT : techniques d'instrumentation, matériaux et contrôles physico-chimiques, mesures et analyses environnementales.",
    apres: "Technicien en métrologie (science de la mesure), en contrôle des matériaux, en laboratoire d'analyse ou en instrumentation, ou poursuite en master ou en école d'ingénieurs.",
    mpc: "Maths et physique-chimie sont deux des trois spécialités conseillées par l'Onisep (avec les sciences de l'ingénieur) : sans doute le BUT le plus proche de ton profil. Moins connu que les BUT de mécanique ou d'électricité, il est de plus en plus demandé : candidate dans plusieurs IUT.",
    w: { PHYS: 1, CHIM: .5, ENER: .4 }, kw: ["recherche", "industrie", "environnement", "biomed"],
    p: { enc: .9, conc: .9, intense: .5, maths: .5, phys: .9, chim: .5, code: .2, ecrit: .2, oral: .2, vente: 0, bureau: .4, terrain: .1, indus: .7, ouvert: .6, gen: .6, integ: 0, sortie: 3 },
    src: { u: "https://www.onisep.fr/ressources/univers-formation/formations/post-bac/but-mesures-physiques-parcours-materiaux-et-controles-physico-chimiques", l: "Fiche Onisep" } },

  { id: "but_geii", nom: "BUT Génie électrique et informatique industrielle (GEII)", duree: "3 ans", sel: 1, selNote: "Demande en hausse ; plus sélectif en Île-de-France", cout: BUT_COST, alt: .7, inge: .5,
    alias: ["GEII", "BUT GEII", "génie électrique"],
    desc: "Électronique, électrotechnique, automatisme, informatique industrielle et systèmes embarqués : du circuit imprimé au robot, avec beaucoup de projets. Trois parcours en 2e année selon l'IUT : automatisme et informatique industrielle, électricité et maîtrise de l'énergie, électronique et systèmes embarqués.",
    apres: "Technicien supérieur en électronique, électrotechnique, automatisme ou informatique industrielle (énergie, transports, industrie), ou poursuite en master ou en école d'ingénieurs.",
    mpc: "Maths et physique-chimie font partie des quatre spécialités conseillées par l'Onisep (avec NSI et sciences de l'ingénieur) : tu n'as besoin ni de sciences de l'ingénieur ni de NSI. Pour qui aime l'électricité, l'électronique et les montages.",
    w: { ENER: 1, NUM: .5, PHYS: .4 }, kw: ["electronique", "robot", "energie", "industrie"],
    p: { enc: .9, conc: .9, intense: .5, maths: .5, phys: .7, chim: 0, code: .5, ecrit: .1, oral: .2, vente: 0, bureau: .5, terrain: .1, indus: .6, ouvert: .6, gen: .5, integ: 0, sortie: 3 },
    src: { u: "https://www.onisep.fr/ressources/univers-formation/formations/post-bac/but-genie-electrique-et-informatique-industrielle-parcours-electricite-et-maitrise-de-l-energie", l: "Fiche Onisep" } },

  { id: "but_info", nom: "BUT Informatique", duree: "3 ans", sel: 2, selNote: "Très demandé", cout: BUT_COST, alt: .7, inge: .5, conseil: ["nsi"],
    alias: ["BUT info", "BUT informatique", "DUT info", "IUT info"],
    desc: "Développement d'applications, bases de données, réseaux, systèmes, gestion de projet, avec des projets en équipe chaque semestre. Quatre parcours en 2e année selon l'IUT : réalisation d'applications, déploiement d'applications sécurisées, gestion des données, intégration et système d'information.",
    apres: "Développeur d'applications, administrateur systèmes et réseaux, administrateur de bases de données, intégrateur ; beaucoup poursuivent en master, en école d'ingénieurs ou en école spécialisée.",
    mpc: "Maths et physique-chimie figurent parmi les spécialités conseillées par l'Onisep, à côté de NSI, sciences de l'ingénieur, SVT et SES. Très demandé : sans NSI, soigne tes notes de maths et montre que tu codes déjà (projets personnels, Python).",
    w: { NUM: 1, MATH: .3 }, kw: ["dev", "ia"],
    p: { enc: .9, conc: .9, intense: .5, maths: .4, phys: 0, chim: 0, code: 1, ecrit: .2, oral: .3, vente: 0, bureau: 1, terrain: 0, indus: 0, ouvert: .5, gen: .4, integ: 0, sortie: 3 },
    src: { u: "https://www.onisep.fr/ressources/univers-formation/formations/post-bac/but-informatique-parcours-realisation-d-applications-conception-developpement-validation", l: "Fiche Onisep" } },

  { id: "but_rt", nom: "BUT Réseaux et télécommunications", duree: "3 ans", sel: 1, cout: BUT_COST, alt: .7, inge: .5,
    alias: ["BUT RT", "réseaux et télécoms", "R&T"],
    desc: "Réseaux informatiques, télécoms, fibre et radio, cybersécurité, objets connectés, cloud : installer, configurer et sécuriser les réseaux. Cinq parcours en 2e année selon l'IUT : cybersécurité, système et cloud, objets connectés, pilotage de projets, réseaux d'opérateurs.",
    apres: "Administrateur réseaux ou systèmes, technicien télécoms et réseaux, technicien en cybersécurité ; poursuite en master, en école d'ingénieurs ou en école de commerce.",
    mpc: "Maths et physique-chimie figurent parmi les spécialités conseillées par l'Onisep (avec NSI, sciences de l'ingénieur, SVT et SES) ; les ondes et l'électricité de la physique y servent, à côté de l'informatique. Moins demandé que le BUT Informatique.",
    w: { NUM: 1, ENER: .6 }, kw: ["ia", "electronique", "dev"],
    p: { enc: .9, conc: .9, intense: .5, maths: .4, phys: .4, chim: 0, code: .7, ecrit: .1, oral: .2, vente: 0, bureau: .8, terrain: .1, indus: .2, ouvert: .5, gen: .4, integ: 0, sortie: 3 },
    src: { u: "https://www.onisep.fr/ressources/univers-formation/formations/post-bac/but-reseaux-et-telecommunications-parcours-cybersecurite", l: "Fiche Onisep" } },

  { id: "but_gc", nom: "BUT Génie civil - construction durable", duree: "3 ans", sel: 2, selNote: "Très demandé, surtout dans les grandes villes", cout: BUT_COST, alt: .7, inge: .5,
    core: ["construction"],
    alias: ["BUT génie civil", "génie civil", "construction durable", "GCCD"],
    desc: "Concevoir, calculer et conduire des chantiers de bâtiments et d'ouvrages : structures, matériaux, équipements techniques, confort thermique et acoustique, maquette numérique du bâtiment (BIM). Quatre parcours en 2e année selon l'IUT : bureaux d'études, travaux de bâtiment, travaux publics, réhabilitation.",
    apres: "Chef de chantier, conducteur de travaux, chargé d'études de prix, dessinateur-projeteur ; poursuite possible en école d'ingénieurs du BTP, en école spécialisée ou en master de génie civil.",
    mpc: "Maths et physique-chimie sont deux des quatre spécialités conseillées par l'Onisep (avec sciences de l'ingénieur et NSI) : forces et énergie servent à dimensionner de vraies structures. Environ 80 % des diplômés qui arrêtent après le BUT ont un emploi salarié un an après (ministère).",
    w: { BAT: 1, MECA: .4, ENER: .2 }, kw: ["construction", "environnement", "energie"],
    p: { enc: .9, conc: .9, intense: .5, maths: .5, phys: .5, chim: .1, code: .1, ecrit: .2, oral: .3, vente: 0, bureau: .4, terrain: .6, indus: .6, ouvert: .5, gen: .4, integ: 0, sortie: 3 },
    src: { u: "https://www.onisep.fr/ressources/univers-formation/formations/post-bac/but-genie-civil-construction-durable-parcours-bureaux-d-etudes-conception", l: "Fiche Onisep" } },

  { id: "but_mt2e", nom: "BUT Métiers de la transition et de l'efficacité énergétiques (MT2E)", duree: "3 ans", sel: 1, cout: BUT_COST, alt: .7, side: true, inge: .5,
    alias: ["MT2E", "transition énergétique", "efficacité énergétique", "GTE", "génie thermique et énergie"],
    desc: "Chauffage, climatisation, énergies renouvelables, rénovation énergétique des bâtiments : thermique, fluides et régulation pour réduire la consommation d'énergie. Quatre parcours en 2e année selon l'IUT : optimisation, réalisation, exploitation ou management de l'énergie.",
    apres: "Technicien en énergétique, chargé d'études en thermique, chargé d'affaires, conseiller énergie ; poursuite en master ou en école d'ingénieurs.",
    mpc: "Maths et physique-chimie sont deux des trois spécialités conseillées par l'Onisep (avec les sciences de l'ingénieur) : la thermodynamique et l'énergie de ton programme servent directement, au service de la transition écologique.",
    w: { ENER: 1, BAT: .5, VIE: .3 }, kw: ["energie", "environnement", "construction"],
    p: { enc: .9, conc: .9, intense: .5, maths: .4, phys: .7, chim: .2, code: .1, ecrit: .2, oral: .3, vente: .1, bureau: .4, terrain: .5, indus: .6, ouvert: .5, gen: .4, integ: 0, sortie: 3 },
    src: { u: "https://www.onisep.fr/ressources/univers-formation/formations/post-bac/but-metiers-de-la-transition-et-de-l-efficacite-energetiques-parcours-optimisation-energetique-pour-le-batiment-et-l-industrie", l: "Fiche Onisep" } },

  { id: "but_chimie", nom: "BUT Chimie", duree: "3 ans", sel: 1, cout: BUT_COST, alt: .6, inge: .5,
    alias: ["BUT chimie", "DUT chimie"],
    desc: "Analyse, synthèse, formulation, matériaux, avec beaucoup de laboratoire : le BUT qui forme les techniciens chimistes. Quatre parcours en 2e année selon l'IUT : chimie industrielle, analyse-contrôle-qualité-environnement, matériaux et produits formulés, synthèse.",
    apres: "Technicien chimiste ou de contrôle qualité, technicien de production, assistant d'ingénieur en recherche et développement ; poursuite en master de chimie ou en école d'ingénieurs.",
    mpc: "Maths et physique-chimie sont en tête des spécialités conseillées par l'Onisep (avec SVT, sciences de l'ingénieur et NSI). Si tu préfères la chimie à la physique et que tu aimes manipuler, c'est le BUT le plus direct.",
    w: { CHIM: 1, PHYS: .3, VIE: .2 }, kw: ["chimie", "sante", "environnement"],
    p: { enc: .9, conc: .9, intense: .5, maths: .3, phys: .4, chim: 1, code: .1, ecrit: .2, oral: .2, vente: 0, bureau: .3, terrain: 0, indus: .8, ouvert: .5, gen: .4, integ: 0, sortie: 3 },
    src: { u: "https://www.onisep.fr/ressources/univers-formation/formations/post-bac/but-chimie-parcours-chimie-industrielle", l: "Fiche Onisep" } },

  { id: "but_gcgp", nom: "BUT Génie chimique - génie des procédés", duree: "3 ans", sel: 1, cout: BUT_COST, alt: .6, side: true, inge: .5,
    alias: ["génie chimique", "génie des procédés", "GCGP"],
    desc: "Passer de l'éprouvette à l'usine : concevoir et piloter des procédés de fabrication (chimie, pharmacie, agroalimentaire, énergie, traitement de l'eau). Proposé dans une douzaine d'IUT, avec trois parcours possibles en 2e année : conception des procédés, pilotage et optimisation, contrôle-qualité-sécurité-environnement.",
    apres: "Technicien de production, de procédés, de laboratoire ou d'environnement ; poursuite en master de génie des procédés ou en école d'ingénieurs (génie chimique, procédés).",
    mpc: "Moins de labo que le BUT Chimie, plus de physique (fluides, thermique) et d'industrie. Maths et physique-chimie sont parmi les spécialités conseillées par l'Onisep (avec SVT et sciences de l'ingénieur).",
    w: { CHIM: 1, ENER: .4, PHYS: .4 }, kw: ["chimie", "industrie", "environnement", "energie"],
    p: { enc: .9, conc: .9, intense: .5, maths: .5, phys: .6, chim: .8, code: .1, ecrit: .2, oral: .2, vente: 0, bureau: .3, terrain: .1, indus: .9, ouvert: .5, gen: .4, integ: 0, sortie: 3 },
    src: { u: "https://www.onisep.fr/ressources/univers-formation/formations/post-bac/but-genie-chimique-genie-des-procedes-parcours-conception-des-procedes-et-innovation-technologique", l: "Fiche Onisep" } },

  { id: "but_gim", nom: "BUT Génie industriel et maintenance (GIM)", duree: "3 ans", sel: 1, cout: BUT_COST, alt: .8, side: true, inge: .5,
    alias: ["GIM", "maintenance industrielle"],
    desc: "Faire fonctionner les installations industrielles : mécanique, électricité, automatisme, énergie, sécurité, et organisation de la maintenance. Deux parcours en 2e année selon l'IUT : ingénierie des systèmes pluritechniques, ou management, méthodes et maintenance innovante.",
    apres: "Technicien ou responsable de maintenance, poste technico-commercial ou d'encadrement (industrie, transports, énergie) ; poursuite en master ou en école d'ingénieurs.",
    mpc: "Polyvalent : environ 83 % des diplômés qui arrêtent après le BUT ont un emploi salarié un an après, l'un des meilleurs taux (ministère). Maths et physique-chimie sont parmi les spécialités conseillées par l'Onisep (avec NSI, sciences de l'ingénieur et SVT).",
    w: { ENER: 1, MECA: .9 }, kw: ["industrie", "energie", "transport", "robot"],
    p: { enc: .9, conc: 1, intense: .5, maths: .4, phys: .6, chim: .1, code: .2, ecrit: .1, oral: .2, vente: 0, bureau: .3, terrain: .4, indus: 1, ouvert: .5, gen: .6, integ: 0, sortie: 3 },
    src: { u: "https://www.onisep.fr/ressources/univers-formation/formations/post-bac/but-genie-industriel-et-maintenance-parcours-ingenierie-des-systemes-pluritechniques", l: "Fiche Onisep" } },

  { id: "but_qlio", nom: "BUT Qualité, logistique industrielle et organisation (QLIO)", duree: "3 ans", sel: 1, cout: BUT_COST, alt: .8, side: true, inge: .5,
    alias: ["QLIO", "logistique industrielle", "qualité"],
    desc: "Organiser la production de biens et de services : qualité, logistique (gestion des flux physiques et d'information), amélioration continue. Quatre parcours en 2e année selon l'IUT : management de la production, qualité et management intégré, supply chain, transformation numérique.",
    apres: "Responsable de production ou d'équipe, animateur qualité-sécurité-environnement, logisticien ; poursuite en master ou en école d'ingénieurs.",
    mpc: "Pour qui aime organiser et optimiser plus que concevoir des pièces. Maths et physique-chimie sont parmi les spécialités conseillées par l'Onisep (avec NSI et sciences de l'ingénieur).",
    w: { ECO: .8, MECA: .6, MATH: .5 }, kw: ["industrie", "entreprise"],
    p: { enc: .9, conc: .9, intense: .4, maths: .5, phys: .2, chim: .1, code: .3, ecrit: .3, oral: .4, vente: .1, bureau: .6, terrain: .3, indus: .7, ouvert: .5, gen: .6, integ: 0, sortie: 3 },
    src: { u: "https://www.onisep.fr/ressources/univers-formation/formations/post-bac/but-qualite-logistique-industrielle-et-organisation-parcours-management-de-la-production", l: "Fiche Onisep" } },

  { id: "but_sd", nom: "BUT Science des données", duree: "3 ans", sel: 2, cout: BUT_COST, alt: .8, inge: .5,
    alias: ["Science des données", "BUT SD", "STID", "data"],
    desc: "Statistiques, programmation, bases de données et restitution des résultats pour aider à la décision, avec beaucoup de projets et des stages. Deux parcours en 2e année selon l'IUT : exploration et modélisation statistique, ou visualisation et conception d'outils décisionnels.",
    apres: "Chargé d'études statistiques, data analyst, statisticien, développeur décisionnel ; beaucoup poursuivent en master, en école d'ingénieurs ou en école de commerce.",
    mpc: "Un des BUT les plus tournés vers les maths : les probas et les statistiques y sont au cœur, et il faut aimer coder. Maths et physique-chimie figurent parmi les spécialités conseillées par l'Onisep (avec sciences de l'ingénieur, NSI, SES et SVT).",
    w: { MATH: 1, NUM: .8, ECO: .3 }, kw: ["ia", "finance", "dev"],
    p: { enc: .9, conc: .8, intense: .5, maths: .8, phys: 0, chim: 0, code: .8, ecrit: .2, oral: .3, vente: 0, bureau: .9, terrain: 0, indus: 0, ouvert: .6, gen: .5, integ: 0, sortie: 3 },
    src: { u: "https://www.onisep.fr/ressources/univers-formation/formations/post-bac/but-science-des-donnees-parcours-exploration-et-modelisation-statistique", l: "Fiche Onisep" } },

  { id: "but_mmi", nom: "BUT Métiers du multimédia et de l'internet (MMI)", duree: "3 ans", sel: 2, selNote: "Très demandé", cout: BUT_COST, alt: .6, inge: 0,
    core: ["design", "sonimage", "dev"],
    alias: ["MMI", "BUT MMI", "multimédia", "web design"],
    desc: "Création numérique (vidéo, son, design graphique), développement web et communication : un BUT entre technique et création. Trois parcours en 2e année selon l'IUT : création numérique, développement web et dispositifs interactifs, stratégie de communication numérique et design d'expérience.",
    apres: "Webdesigner, développeur web, chargé de communication numérique, motion designer ; poursuite en master, en école d'ingénieurs ou en école spécialisée.",
    mpc: "Une ouverture si la création t'attire autant que la technique. Très sélectif : les IUT regardent surtout tes notes (maths, français) et un projet de formation motivé ; mentionne ce que tu as déjà créé (vidéos, sites, graphismes) dans tes activités et centres d'intérêt.",
    w: { CREA: 1, NUM: .7 }, kw: ["sonimage", "design", "dev"],
    p: { enc: .9, conc: .9, intense: .5, maths: .2, phys: .1, chim: 0, code: .6, ecrit: .3, oral: .4, vente: .1, bureau: .9, terrain: 0, indus: 0, ouvert: .5, gen: .5, integ: 0, sortie: 3 },
    src: { u: "https://www.onisep.fr/ressources/univers-formation/formations/post-bac/but-metiers-du-multimedia-et-de-l-internet-parcours-developpement-web-et-dispositifs-interactifs", l: "Fiche Onisep" } },

  { id: "but_hse", nom: "BUT Hygiène, sécurité, environnement (HSE)", duree: "3 ans", sel: 1, cout: BUT_COST, alt: .6, side: true, inge: .5,
    alias: ["HSE", "hygiène sécurité environnement", "prévention des risques"],
    desc: "Prévenir les risques au travail, pour l'environnement et pour la population : risques industriels et chimiques, pollutions, santé et sécurité au travail, réglementation, avec du droit, de la physique, de la chimie et de la biologie. Un seul parcours : science du danger et management des risques.",
    apres: "Préventeur ou animateur HSE dans l'industrie, le BTP ou les collectivités, technicien en traitement des déchets ou en radioprotection ; poursuite en master, en école d'ingénieurs ou en école de commerce.",
    mpc: "Un mélange de physique, de chimie, de biologie et de droit. Maths et physique-chimie sont les deux premières spécialités conseillées par l'Onisep (avec SVT, biologie-écologie et sciences de l'ingénieur).",
    w: { VIE: .8, CHIM: .5, ENER: .3 }, kw: ["environnement", "industrie", "sante"],
    p: { enc: .9, conc: .9, intense: .4, maths: .3, phys: .4, chim: .5, code: .1, ecrit: .5, oral: .4, vente: 0, bureau: .4, terrain: .7, indus: .6, ouvert: .5, gen: .5, integ: 0, sortie: 3 },
    src: { u: "https://www.onisep.fr/ressources/univers-formation/formations/post-bac/but-hygiene-securite-environnement-parcours-science-du-danger-et-management-des-risques-professionnels-technologiques-et-environnementaux", l: "Fiche Onisep" } }
]);
