// Université : cycles préparatoires, licences, parcours renforcés. Vérifié le 5 octobre 2026 (voir dev/facts_fac_sante_crea.md).
add("fac", [
  { id: "cupge", nom: "CUPGE (cycle universitaire préparatoire aux grandes écoles)", duree: "2 ans (parfois 3 ans selon l'option)", sel: 2, selNote: "Sélection sur dossier, quelques dizaines de places par université", cout: FAC_COST, alt: 0, inge: 1,
    alias: ["CUPGE", "cycle préparatoire universitaire", "prépa à la fac", "prépa universitaire"],
    desc: "Une prépa à l'université : petits groupes, devoirs surveillés réguliers, programme proche de celui des prépas, tout en validant les deux premières années d'une licence (maths, physique, mécanique… selon les universités). On y entre sur dossier, via Parcoursup.",
    apres: "Entrée en école d'ingénieurs sur dossier ou concours, selon l'université et l'école (par exemple INSA, Polytech ou Arts et Métiers), ou 3e année de licence puis master.",
    mpc: "Maths et physique-chimie : c'est le profil attendu. Une prépa presque gratuite qui garde une porte de sortie : sans école à la fin, tu continues en licence. Pratique si tu hésites entre école d'ingénieurs et recherche.",
    w: { MATH: 1, PHYS: .9, CHIM: .3 }, kw: ["recherche", "energie", "aero"],
    p: { enc: .8, conc: .3, intense: .8, maths: .9, phys: .8, chim: .3, code: .3, ecrit: .2, oral: .4, vente: 0, bureau: .8, terrain: 0, indus: 0, ouvert: 1, gen: 1, integ: 0, sortie: 3, concours: .5, fac: .5 },
    src: { u: "https://odf.u-paris.fr/fr/offre-de-formation/licence-XA/sciences-technologies-sante-STS/physique-K1T0IUJ7/licence-physique-cycle-universitaire-preparatoire-aux-grandes-ecoles-cupge-JRM6Q50Z.html", l: "Université Paris Cité" } },

  { id: "cmi", nom: "CMI (cursus master en ingénierie)", duree: "5 ans (licence + master renforcés)", sel: 2, selNote: "Sélection sur dossier, puis entretien", cout: "Environ 280 €/an en licence et 360 € en master, CVEC comprise (0 € si boursier)", alt: .1, side: true, inge: .5,
    alias: ["CMI", "cursus master en ingénierie", "réseau Figure", "Figure"],
    desc: "Un parcours renforcé de 5 ans à l'université, labellisé par le réseau Figure : licence puis master, avec environ 20 % d'heures en plus, au moins 28 semaines de stage et 3 mois à l'international. Spécialités variées selon les universités (mécanique, électronique, informatique, physique, chimie…).",
    apres: "Emploi dans l'industrie ou la recherche, ou doctorat. Le CMI est un label ajouté à la licence et au master : ce n'est pas un titre d'ingénieur délivré par une école accréditée par la CTI (Commission des titres d'ingénieur).",
    mpc: "Peu connu et presque gratuit, avec plus d'heures, de projets et de stages qu'une licence classique. Les CMI scientifiques (physique, mécanique, électronique…) conviennent bien à un profil maths + physique-chimie : regarde les cursus du réseau Figure dans les universités qui t'intéressent.",
    w: { PHYS: .8, MATH: .8, MECA: .6, NUM: .6, CHIM: .4 }, kw: ["recherche", "industrie", "environnement"],
    p: { enc: .6, conc: .6, intense: .7, maths: .7, phys: .7, chim: .3, code: .4, ecrit: .3, oral: .3, vente: 0, bureau: .7, terrain: .1, indus: .2, ouvert: .8, gen: .7, integ: 0, sortie: 5, fac: .5 },
    src: { u: "https://www.reseau-figure.fr/les-cursus-master-en-ingenierie", l: "Réseau Figure" } },

  { id: "dl_sciences", nom: "Doubles licences et licences renforcées scientifiques (maths-physique, maths-informatique, physique-chimie…)", duree: "3 ans", sel: 3, selNote: "Sélection sur dossier, places limitées", cout: FAC_COST, alt: 0, inge: .5, conseil: ["expertes"],
    alias: ["double licence", "licence renforcée", "maths-physique", "maths-info", "magistère"],
    desc: "Deux disciplines menées de front, ou un parcours renforcé, en petits effectifs et sur dossier : beaucoup de travail et un niveau d'exigence élevé. Les intitulés, les places et les combinaisons varient beaucoup d'une université à l'autre.",
    apres: "Masters sélectifs, ENS par concours ou sur dossier à partir de la L2 ou de la L3, écoles d'ingénieurs en admission sur titre.",
    mpc: "Taillé pour un bon dossier en maths et en physique-chimie qui aime la théorie. Les maths expertes sont un vrai plus.",
    w: { MATH: 1, PHYS: 1, NUM: .3 }, kw: ["recherche", "ia", "enseigner"],
    p: { enc: .6, conc: .2, intense: .8, maths: 1, phys: .8, chim: .2, code: .3, ecrit: .2, oral: .3, vente: 0, bureau: .9, terrain: 0, indus: 0, ouvert: 1, gen: .8, integ: 0, sortie: 3, fac: .5 },
    src: { u: "https://www.onisep.fr/formation/les-principaux-domaines-de-formation/les-licences-de-sciences", l: "Onisep" } },

  { id: "lic_maths", nom: "Licence Mathématiques", duree: "3 ans", sel: 1, selNote: "Non sélective sur Parcoursup, mais les places sont parfois limitées selon les universités", cout: FAC_COST, alt: 0, inge: .5, conseil: ["expertes"],
    alias: ["licence de maths", "licence maths", "fac de maths"],
    desc: "Analyse, algèbre, probabilités et un peu d'informatique : des maths de plus en plus abstraites, avec la démonstration au cœur. En 3e année, selon les universités : parcours fondamentaux, appliqués (actuariat, finance…), bidisciplinaires (maths-info…) ou renforcés pour préparer les écoles d'ingénieurs.",
    apres: "Masters de maths, de statistique, d'actuariat, de finance, d'informatique ou d'enseignement (prof de maths) ; écoles d'ingénieurs ou de statistique (ENSAI, ENSAE) en admission après la licence.",
    mpc: "Pour qui aime raisonner et démontrer plus que calculer. Les maths expertes (nombres complexes, arithmétique, matrices) aident à démarrer.",
    w: { MATH: 1, NUM: .3 }, kw: ["recherche", "enseigner", "finance", "ia"],
    p: { enc: .3, conc: .1, intense: .6, maths: 1, phys: .2, chim: 0, code: .3, ecrit: .2, oral: .2, vente: 0, bureau: .9, terrain: 0, indus: 0, ouvert: .9, gen: .6, integ: 0, sortie: 3, fac: 1 },
    src: { u: "https://www.onisep.fr/ressources/univers-formation/formations/post-bac/licence-mention-mathematiques", l: "Fiche Onisep" } },

  { id: "lic_phys", nom: "Licence Physique ou Physique, chimie", duree: "3 ans", sel: 1, cout: FAC_COST, alt: 0, inge: .5,
    alias: ["licence de physique", "licence physique", "licence physique-chimie", "fac de physique"],
    desc: "Mécanique, électromagnétisme, optique, thermodynamique, physique quantique, avec beaucoup de maths et des TP. Certaines universités proposent la mention Physique, chimie, qui garde les deux disciplines.",
    apres: "Masters de physique (recherche, énergie, matériaux, astrophysique, optique), master d'enseignement (prof de physique-chimie), écoles d'ingénieurs sur titre, doctorat.",
    mpc: "La suite naturelle si la physique te passionne et que tu veux comprendre autant qu'appliquer. Un bon niveau en maths est indispensable.",
    w: { PHYS: 1, MATH: .6, ENER: .3 }, kw: ["recherche", "energie", "aero", "enseigner"],
    p: { enc: .3, conc: .2, intense: .6, maths: .7, phys: 1, chim: .3, code: .3, ecrit: .2, oral: .2, vente: 0, bureau: .8, terrain: 0, indus: .2, ouvert: .9, gen: .6, integ: 0, sortie: 3, fac: 1 },
    src: { u: "https://www.onisep.fr/ressources/univers-formation/formations/post-bac/licence-mention-physique", l: "Fiche Onisep" } },

  { id: "lic_info", nom: "Licence Informatique", duree: "3 ans", sel: 1, selNote: "Non sélective sur Parcoursup, mais très demandée dans certaines universités", cout: FAC_COST, alt: .2, inge: .5, conseil: ["nsi"],
    alias: ["licence info", "licence informatique", "fac d'info"],
    desc: "Programmation, algorithmique, bases de données, réseaux, systèmes, avec une bonne part de maths (logique, maths discrètes) les premières années.",
    apres: "Masters d'informatique (IA, cybersécurité, génie logiciel, données), écoles d'ingénieurs sur titre, ou emploi de développeur après une licence pro.",
    mpc: "Accessible sans NSI, mais il faut aimer coder : commence Python avant la rentrée si tu n'as jamais programmé.",
    w: { NUM: 1, MATH: .5 }, kw: ["dev", "ia", "electronique"],
    p: { enc: .3, conc: .5, intense: .6, maths: .6, phys: 0, chim: 0, code: 1, ecrit: .2, oral: .2, vente: 0, bureau: 1, terrain: 0, indus: 0, ouvert: .8, gen: .5, integ: 0, sortie: 3, fac: 1 },
    src: { u: "https://www.onisep.fr/ressources/univers-formation/formations/post-bac/licence-mention-informatique", l: "Fiche Onisep" } },

  { id: "lic_spi", nom: "Licence Sciences pour l'ingénieur (ou Mécanique, ou Électronique, énergie électrique, automatique)", duree: "3 ans", sel: 1, cout: FAC_COST, alt: .2, inge: .5,
    alias: ["licence SPI", "sciences pour l'ingénieur", "licence mécanique", "licence EEA", "licence EEEA", "licence électronique"],
    desc: "Les bases de l'ingénieur à l'université : mécanique, électronique, énergie, automatique, robotique… selon les parcours, avec des projets et des TP. Selon l'université, la mention s'appelle Sciences pour l'ingénieur, Mécanique, ou Électronique, énergie électrique, automatique.",
    apres: "Masters en mécanique, énergie, électronique, robotique ; écoles d'ingénieurs sur titre, ou parcours renforcé qui prépare aux concours ; licences pro.",
    mpc: "Pour aller vers l'ingénierie sans prépa ni école payante : la mécanique et l'énergie de terminale servent directement.",
    w: { MECA: 1, ENER: .9, PHYS: .5, MATH: .4 }, kw: ["industrie", "robot", "energie", "electronique"],
    p: { enc: .4, conc: .6, intense: .5, maths: .6, phys: .8, chim: .1, code: .3, ecrit: .2, oral: .2, vente: 0, bureau: .6, terrain: 0, indus: .4, ouvert: .7, gen: .6, integ: 0, sortie: 3, fac: 1 },
    src: { u: "https://www.onisep.fr/ressources/univers-formation/formations/post-bac/licence-mention-sciences-pour-l-ingenieur", l: "Fiche Onisep" } },

  { id: "lic_chimie", nom: "Licence Chimie", duree: "3 ans", sel: 1, cout: FAC_COST, alt: .1, inge: .5,
    alias: ["licence chimie", "licence de chimie", "fac de chimie"],
    desc: "Chimie organique, inorganique, analytique et physique, avec beaucoup de TP en laboratoire, et des maths et de la physique les premières années.",
    apres: "Masters de chimie (matériaux, analyse, formulation, environnement, pharmaceutique), licence pro (chimie, contrôle qualité), écoles de chimie (Fédération Gay-Lussac) en admission parallèle, enseignement.",
    mpc: "Si la chimie est ta partie préférée de physique-chimie et que tu aimes manipuler en labo.",
    w: { CHIM: 1, PHYS: .4, VIE: .2 }, kw: ["chimie", "environnement", "sante"],
    p: { enc: .3, conc: .5, intense: .5, maths: .4, phys: .5, chim: 1, code: .1, ecrit: .2, oral: .2, vente: 0, bureau: .4, terrain: 0, indus: .5, ouvert: .7, gen: .4, integ: 0, sortie: 3, fac: 1 },
    src: { u: "https://www.onisep.fr/ressources/univers-formation/formations/post-bac/licence-mention-chimie", l: "Fiche Onisep" } },

  { id: "lic_terre", nom: "Licence Sciences de la Terre (géosciences)", duree: "3 ans", sel: 1, cout: FAC_COST, alt: 0, side: true, inge: 0, conseil: ["svt"],
    alias: ["géologie", "géosciences", "sciences de la Terre", "volcanologie"],
    desc: "Géologie, minéralogie, paléontologie, hydrologie : de la physique et de la chimie appliquées à la planète, avec des stages de terrain. La 1re année se fait souvent dans un portail commun avec la physique et la chimie.",
    apres: "Masters en géosciences, environnement, risques naturels, hydrogéologie ou énergie ; écoles d'ingénieurs en admission parallèle après la L2 ou la L3 ; enseignement.",
    mpc: "Une voie méconnue où ta physique-chimie sert à comprendre la Terre. La SVT aide, mais la physique et la chimie comptent autant.",
    w: { VIE: .8, PHYS: .7, CHIM: .4 }, kw: ["environnement", "recherche", "energie"],
    p: { enc: .3, conc: .6, intense: .5, maths: .4, phys: .6, chim: .4, code: .2, ecrit: .3, oral: .2, vente: 0, bureau: .4, terrain: .7, indus: .1, ouvert: .7, gen: .4, integ: 0, sortie: 3, fac: 1 },
    src: { u: "https://www.onisep.fr/ressources/univers-formation/formations/post-bac/licence-mention-sciences-de-la-terre", l: "Fiche Onisep" } },

  { id: "lic_eco_maths", nom: "Licence MIASHS (mathématiques et informatique appliquées aux sciences humaines et sociales) ou double licence maths-économie", duree: "3 ans", sel: 2, selNote: "MIASHS non sélective ; les doubles licences sont souvent sélectives sur dossier", cout: FAC_COST, alt: 0, side: true, inge: 0,
    core: ["finance", "societe", "ia", "entreprise"],
    alias: ["MIASHS", "maths-éco", "double licence maths-économie", "licence d'économie", "économie", "ENSAE", "ENSAI"],
    desc: "Des maths et de l'informatique appliquées à l'économie et aux sciences sociales (MIASHS), ou une double licence qui mène les deux disciplines à haut niveau : statistique, économétrie, modélisation.",
    apres: "Masters de statistique, data science, économie, finance ou actuariat ; écoles de statistique comme l'ENSAI ou l'ENSAE, en admission après la licence ou le master 1.",
    mpc: "Une ouverture si l'économie ou la société t'intéressent autant que les maths. Onisep préconise une très bonne maîtrise des maths et de l'informatique au lycée : la physique y sert peu, mais ton niveau en maths est un vrai atout.",
    w: { MATH: 1, ECO: .8, NUM: .4 }, kw: ["finance", "ia", "societe", "entreprise"],
    p: { enc: .4, conc: .4, intense: .6, maths: .9, phys: 0, chim: 0, code: .5, ecrit: .4, oral: .2, vente: 0, bureau: .9, terrain: 0, indus: 0, ouvert: .9, gen: .7, integ: 0, sortie: 3, fac: .8 },
    src: { u: "https://www.onisep.fr/ressources/univers-formation/formations/post-bac/licence-mention-mathematiques-et-informatique-appliquees-aux-sciences-humaines-et-sociales", l: "Fiche Onisep" } },

  { id: "staps", nom: "Licence STAPS (sciences et techniques des activités physiques et sportives)", duree: "3 ans", sel: 2, selNote: "Non sélective sur Parcoursup, mais très demandée dans beaucoup d'universités (places limitées)", cout: FAC_COST, alt: .1, inge: 0,
    core: ["sport"],
    alias: ["STAPS", "fac de sport", "prof de sport", "coach sportif", "préparateur physique"],
    desc: "Le sport sous tous ses angles : physiologie, biomécanique, psychologie, entraînement, pratique sportive intensive. Spécialités en 3e année, selon les universités : entraînement, activité physique adaptée et santé, management du sport, enseignement, ergonomie.",
    apres: "Éducateur sportif, préparateur physique, enseignant d'EPS (après un master), métiers de la santé par le sport, management du sport. Une des voies actuelles vers les instituts de kinésithérapie (1re ou 2e année selon l'université) ; la réforme de 2027 doit changer cet accès.",
    mpc: "La biomécanique et la physiologie demandent de la physique et un peu de bio : ton profil scientifique est un atout. Il faut une vraie pratique sportive.",
    w: { HUM: 1, VIE: .7, PHYS: .2 }, kw: ["sport", "sante", "enseigner"],
    p: { enc: .4, conc: .7, intense: .5, maths: .2, phys: .3, chim: .1, code: 0, ecrit: .4, oral: .4, vente: 0, bureau: .2, terrain: .9, indus: 0, ouvert: .5, gen: .4, integ: 0, sortie: 3, fac: 1 },
    src: { u: "https://www.onisep.fr/formation/les-principaux-domaines-de-formation/les-formations-en-sport/j-opte-pour-les-formations-sport-a-l-universite/les-licences-staps", l: "Onisep" } },

  { id: "lpe", nom: "Licence Professorat des écoles", duree: "3 ans, puis 2 ans de master (payé si tu réussis le concours)", sel: 2, cout: FAC_COST, alt: 0, side: true, inge: 0,
    core: ["enseigner"],
    alias: ["professeur des écoles", "prof des écoles", "instituteur", "institutrice"],
    desc: "Nouvelle licence ouverte sur Parcoursup depuis la rentrée 2026 pour devenir prof des écoles, avec au moins 10 semaines de stage en école. Le concours se passe en fin de 3e année ; si tu as validé ta 1re et ta 2e année, tu peux, sous certaines conditions, être dispensé des épreuves écrites.",
    apres: "Professeur des écoles. Une fois le concours réussi, tu fais ton master en étant rémunéré.",
    mpc: "Formation polyvalente (français, maths, sciences, sport, arts) : les profils scientifiques y sont recherchés pour enseigner les maths et les sciences. Il faut aimer les enfants autant que transmettre.",
    w: { HUM: 1, MATH: .2 }, kw: ["enseigner"],
    p: { enc: .5, conc: .5, intense: .5, maths: .4, phys: .2, chim: .1, code: 0, ecrit: .6, oral: .7, vente: 0, bureau: .3, terrain: .7, indus: 0, ouvert: .2, gen: .6, integ: 0, sortie: 5, fac: 1 },
    src: { u: "https://www.onisep.fr/ressources/univers-formation/formations/post-bac/licence-mention-professorat-des-ecoles", l: "Fiche Onisep" } }
]);
