// Prépas scientifiques (CPGE) et prépa ECG. Faits vérifiés en octobre 2026 : voir dev/facts_prepa_ingpub.md.
add("prepa", [
  { id: "mpsi", nom: "Prépa MPSI (maths, physique et sciences de l'ingénieur)", duree: "2 ans", sel: 2, selNote: "Sur dossier via Parcoursup : très sélective dans les lycées les plus demandés, plus accessible ailleurs", cout: PREPA_COST, alt: 0, inge: 1, conseil: ["expertes"],
    alias: ["MPSI", "prépa MP", "maths sup", "math sup", "CPGE", "classe préparatoire", "prépa scientifique"],
    desc: "Beaucoup de maths et de physique-chimie, de l'informatique (Python) et, selon l'option, des sciences industrielles de l'ingénieur ou plus d'informatique. Colles (petits oraux) régulières et devoirs surveillés. En 2e année : MP (maths-physique) ou PSI (physique et sciences de l'ingénieur).",
    apres: "Concours des écoles d'ingénieurs (Polytechnique, Centrale-Supélec, Mines-Ponts, CCINP, Mines-Télécom…) et des ENS (écoles normales supérieures). Les 2 années valident 120 crédits ECTS, ce qui facilite une réorientation en licence.",
    mpc: "C'est le profil attendu, dans une prépa très tournée vers les maths. L'option maths expertes est vivement conseillée sans être obligatoire : sans elle, regarde avant la rentrée les nombres complexes, l'arithmétique et les matrices.",
    w: { MATH: 1, PHYS: .7, MECA: .2, ENER: .2 }, kw: ["recherche", "aero", "ia", "energie"],
    p: { enc: 1, conc: .2, intense: 1, maths: 1, phys: .8, chim: .2, code: .3, ecrit: .2, oral: .5, vente: 0, bureau: .9, terrain: 0, indus: 0, ouvert: 1, gen: 1, integ: 0, sortie: 5, concours: 1, prepa: 1 },
    src: { u: "https://www.onisep.fr/ressources/univers-formation/formations/post-bac/classe-preparatoire-mathematiques-physique-et-sciences-de-l-ingenieur-mpsi-1re-annee-option-sciences-industrielles-de-l-ingenieur", l: "Fiche Onisep" } },

  { id: "pcsi", nom: "Prépa PCSI (physique, chimie et sciences de l'ingénieur)", duree: "2 ans", sel: 2, selNote: "Sur dossier via Parcoursup : très sélective dans les lycées les plus demandés, plus accessible ailleurs", cout: PREPA_COST, alt: 0, inge: 1, conseil: ["expertes"],
    alias: ["PCSI", "prépa PC", "prépa physique-chimie", "CPGE", "classe préparatoire", "prépa scientifique"],
    desc: "Maths, physique et chimie en parts importantes, avec des TP (travaux pratiques) de physique et de chimie, de l'informatique (Python) et des sciences de l'ingénieur. Colles (petits oraux) régulières. En 2e année : PC (physique-chimie) ou PSI (physique et sciences de l'ingénieur).",
    apres: "Concours des écoles d'ingénieurs généralistes et de chimie (Centrale-Supélec, Mines-Ponts, CCINP, Mines-Télécom…) et des ENS (écoles normales supérieures). Les 2 années valident 120 crédits ECTS, ce qui facilite une réorientation en licence.",
    mpc: "Maths + physique-chimie est le profil attendu, et la chimie fait partie du nom comme du programme. L'option maths expertes est conseillée sans être obligatoire. À choisir si tu aimes autant la physique et la chimie que les maths.",
    w: { PHYS: 1, MATH: .7, CHIM: .7 }, kw: ["recherche", "chimie", "energie"],
    p: { enc: 1, conc: .3, intense: 1, maths: .8, phys: 1, chim: .7, code: .2, ecrit: .2, oral: .5, vente: 0, bureau: .8, terrain: 0, indus: .2, ouvert: 1, gen: 1, integ: 0, sortie: 5, concours: 1, prepa: 1 },
    src: { u: "https://www.onisep.fr/ressources/univers-formation/formations/post-bac/classe-preparatoire-physique-chimie-et-sciences-de-l-ingenieur-pcsi-1re-annee", l: "Fiche Onisep" } },

  { id: "mp2i", nom: "Prépa MP2I (maths, physique, ingénierie et informatique)", duree: "2 ans", sel: 3, selNote: "Une quarantaine de classes seulement, très demandées (en 2023 : environ 37 000 vœux pour environ 1 350 places)", cout: PREPA_COST, alt: 0, inge: 1, conseil: ["expertes"],
    alias: ["MP2I", "MPI", "prépa info", "prépa informatique", "CPGE", "classe préparatoire", "prépa scientifique"],
    desc: "Créée en 2021 : beaucoup de maths, une grosse part d'informatique (algorithmique, programmation, bases de données), de la physique et un peu d'ingénierie. Colles (petits oraux) régulières. En 2e année : MPI (maths, physique, informatique) le plus souvent, ou MP ou PSI.",
    apres: "Concours des écoles d'ingénieurs avec des épreuves d'informatique (Polytechnique, ENS, Centrale-Supélec, Mines-Ponts, CCINP, Mines-Télécom…), surtout via la 2e année MPI. Les 2 années valident 120 crédits ECTS, ce qui facilite une réorientation en licence de maths ou d'informatique.",
    mpc: "Maths + physique-chimie est un profil accepté, la NSI n'est pas exigée ; les maths expertes sont un atout sans être obligatoires. Si tu n'as jamais programmé, mets-toi à Python avant la rentrée, et prévois des vœux de repli en MPSI ou PCSI vu la forte demande.",
    w: { NUM: 1, MATH: 1, PHYS: .4 }, kw: ["ia", "dev", "recherche"],
    p: { enc: 1, conc: .2, intense: 1, maths: 1, phys: .6, chim: 0, code: .9, ecrit: .2, oral: .5, vente: 0, bureau: .9, terrain: 0, indus: 0, ouvert: .9, gen: .7, integ: 0, sortie: 5, concours: 1, prepa: 1 },
    src: { u: "https://www.onisep.fr/ressources/univers-formation/formations/post-bac/classe-preparatoire-mathematiques-physique-ingenierie-et-informatique-mp2i-1re-annee", l: "Fiche Onisep" } },

  { id: "ptsi", nom: "Prépa PTSI (physique, technologie et sciences de l'ingénieur)", duree: "2 ans", sel: 2, selNote: "Souvent moins demandée que MPSI et PCSI", cout: PREPA_COST, alt: 0, inge: 1, conseil: ["expertes"],
    alias: ["PTSI", "prépa PT", "PT", "banque PT", "Arts et Métiers", "CPGE", "classe préparatoire", "prépa scientifique"],
    desc: "Une prépa plus concrète : maths, physique-chimie et sciences industrielles de l'ingénieur (mécanique, automatique, conception sur ordinateur) à parts proches, environ 8 à 10 h par semaine chacune, avec des projets. Colles (petits oraux) régulières. En 2e année : PT (physique et technologie) ou PSI.",
    apres: "Concours de la banque PT, qui ouvre plus de cent écoles d'ingénieurs (Arts et Métiers en tête, mais aussi des écoles Centrale, des Mines, Polytech, des INSA, l'ENS Paris-Saclay…) avec un nombre de places élevé par rapport au nombre de candidats.",
    mpc: "Maths + physique-chimie est accepté : la spécialité SI n'est pas indispensable, et les maths expertes sont un plus. Idéale si tu aimes la mécanique, la conception et les projets plus que la théorie pure.",
    w: { MECA: 1, MATH: .7, PHYS: .6, ENER: .3 }, kw: ["aero", "auto", "industrie", "robot"],
    p: { enc: 1, conc: .6, intense: .9, maths: .8, phys: .7, chim: .1, code: .3, ecrit: .2, oral: .4, vente: 0, bureau: .7, terrain: 0, indus: .4, ouvert: .9, gen: .8, integ: 0, sortie: 5, concours: 1, prepa: 1 },
    src: { u: "https://www.onisep.fr/ressources/univers-formation/formations/post-bac/classe-preparatoire-physique-technologie-et-sciences-de-l-ingenieur-ptsi-1re-annee", l: "Fiche Onisep" } },

  { id: "bcpst", nom: "Prépa BCPST (biologie, chimie, physique, sciences de la Terre)", duree: "2 ans", sel: 2, cout: PREPA_COST, alt: 0, inge: 1, conseil: ["svt", "expertes"],
    core: ["agro", "environnement", "sante"],
    alias: ["BCPST", "prépa agro", "prépa véto", "agro-véto", "AgroParisTech", "CPGE", "classe préparatoire", "prépa biologie"],
    desc: "Maths, physique-chimie et SVT (biologie et géologie) à parts proches, environ 7 à 8 h par semaine chacune, avec des TP (travaux pratiques) et des sorties sur le terrain. Colles (petits oraux) régulières.",
    apres: "Concours des écoles d'agronomie (AgroParisTech…), des 4 écoles vétérinaires, des écoles de géologie, eau et environnement (concours G2E) et des ENS (écoles normales supérieures). Les 2 années valident 120 crédits ECTS, ce qui facilite une réorientation en licence.",
    mpc: "Maths + physique-chimie est une paire acceptée, mais la SVT occupe à peu près autant d'heures que les maths : sans elle, prévois un rattrapage en biologie et en géologie. Les maths expertes sont valorisées ; à regarder si le vivant te plaît vraiment.",
    w: { VIE: 1, CHIM: .6, PHYS: .5, MATH: .4 }, kw: ["agro", "environnement", "sante", "recherche"],
    p: { enc: 1, conc: .4, intense: 1, maths: .6, phys: .6, chim: .7, code: .1, ecrit: .4, oral: .5, vente: 0, bureau: .6, terrain: .3, indus: .2, ouvert: .9, gen: .8, integ: 0, sortie: 5, concours: 1, prepa: 1 },
    src: { u: "https://www.onisep.fr/ressources/univers-formation/formations/post-bac/classe-preparatoire-biologie-chimie-physique-et-sciences-de-la-terre-bcpst-1re-annee", l: "Fiche Onisep" } },

  { id: "ecg", nom: "Prépa ECG, option maths approfondies (économique et commerciale générale)", duree: "2 ans", sel: 2, cout: PREPA_COST, alt: 0, side: true, inge: 0, conseil: ["expertes"],
    core: ["finance", "entreprise", "societe"],
    alias: ["ECG", "prépa HEC", "prépa commerce", "prépa éco", "HEC", "ESSEC", "ESCP", "EDHEC", "ENSAE", "école de commerce", "BCE", "CPGE", "classe préparatoire"],
    desc: "Maths approfondies, économie-sociologie-histoire (ESH) ou histoire-géographie-géopolitique (HGG), lettres et philosophie (culture générale) et deux langues vivantes. Colles (petits oraux) régulières et beaucoup d'écrit.",
    apres: "Concours des écoles de commerce (HEC, ESSEC, ESCP, EDHEC… via les banques d'épreuves BCE et Ecricome) et de l'ENSAE Paris (école de statistique et d'économie). Les 2 années valident 120 crédits ECTS, ce qui facilite une réorientation en licence.",
    mpc: "Une vraie option si la finance ou l'entreprise t'attirent plus que les sciences : maths + physique-chimie est une combinaison acceptée, et les maths approfondies conviennent surtout à ceux qui ont les maths expertes. Mais l'économie, l'histoire et l'écrit comptent beaucoup, et la physique s'arrête.",
    w: { ECO: 1, MATH: .8 }, kw: ["finance", "entreprise", "societe", "international"],
    p: { enc: 1, conc: .3, intense: 1, maths: .9, phys: 0, chim: 0, code: .2, ecrit: .8, oral: .6, vente: .1, bureau: .9, terrain: 0, indus: 0, ouvert: .9, gen: .9, integ: 0, sortie: 5, concours: 1, prepa: 1 },
    src: { u: "https://www.onisep.fr/ressources/univers-formation/formations/post-bac/classe-preparatoire-economique-et-commerciale-generale-1re-annee", l: "Fiche Onisep" } }
]);
