// Écoles d'ingénieurs privées qui recrutent après le bac. Vérifié le 5 octobre 2026 (voir dev/facts_ingpriv.md).
add("ingpriv", [
  { id: "ing_aero", nom: "Écoles d'ingénieurs post-bac en aéronautique, spatial et automobile (ESTACA, IPSA, ELISA Aerospace…)", duree: "5 ans (2 ans de cycle préparatoire intégré + 3 ans de cycle ingénieur)", sel: 2, selNote: "Concours post-bac : Avenir (ESTACA), Advance (IPSA), Puissance Alpha (ELISA) ; dossier et QCM, entretien pour certains profils", cout: "Environ 8 400 à 11 400 € par an selon l'école (ESTACA : 10 130 €) ; gratuit en apprentissage, possible dès le cycle ingénieur à l'IPSA", alt: .3, inge: 1,
    core: ["aero", "auto", "transport"],
    alias: ["ESTACA", "IPSA", "ELISA", "ELISA Aerospace", "école aéro", "école aéronautique", "école automobile", "école spatiale", "école de transports"],
    desc: "Des écoles privées spécialisées dans les transports dès l'entrée : ESTACA (spatial, aéronautique, automobile, ferroviaire, naval), IPSA (air, espace, mobilités) et ELISA Aerospace (aéronautique, spatial, drones). Projets, stages et séjour à l'étranger au programme de l'ESTACA et d'ELISA.",
    apres: "Ingénieur en conception, essais, production ou maintenance chez les constructeurs et équipementiers (Airbus, Safran, Dassault, Renault, Stellantis, Alstom, Naval Group…) ou dans l'ingénierie. À l'ESTACA, près de la moitié des diplômés travaillent en recherche et développement.",
    mpc: "Ton combo est celui qu'on attend : l'ESTACA demande maths + une 2e spécialité scientifique, ELISA conseille maths + physique-chimie ou sciences de l'ingénieur, et l'IPSA conseille fortement les maths expertes. À l'ESTACA, tu ne choisis ta filière qu'en fin de 1re année ; compare les frais avec les voies publiques (INSA, Polytech, prépa).",
    w: { MECA: 1, PHYS: .4, ENER: .3 }, kw: ["aero", "auto", "transport", "industrie"],
    p: { enc: .8, conc: .7, intense: .7, maths: .7, phys: .7, chim: .1, code: .3, ecrit: .2, oral: .3, vente: 0, bureau: .6, terrain: .1, indus: .5, ouvert: .3, gen: .2, integ: 1, sortie: 5, concours: 1, prive: 1 },
    src: { u: "https://www.estaca.fr/admissions/terminales/", l: "ESTACA" } },

  { id: "ing_gen", nom: "Écoles d'ingénieurs post-bac généralistes privées (EPF, ESILV, ESME, ECE, EIGSI, ESIGELEC, Junia HEI, ECAM…)", duree: "5 ans (prépa intégrée de 2 ans + cycle ingénieur de 3 ans)", sel: 2, selNote: "Concours post-bac (Avenir, Advance ou Puissance Alpha selon l'école) ou dossier et entretien (ECAM)", cout: "Souvent 8 000 à 12 000 € par an selon l'école (prépas moins chères à l'ECAM, dès environ 5 100 €) ; gratuit en apprentissage ; plusieurs écoles réduisent les frais des élèves boursiers", alt: .5, inge: 1,
    alias: ["EPF", "ESILV", "EIGSI", "ESME", "ESME Sudria", "Junia", "HEI", "Junia HEI", "ECAM", "ECAM LaSalle", "ESIGELEC", "ECE", "ECE Paris", "école d'ingénieurs généraliste"],
    desc: "Des écoles privées qui recrutent après le bac et gardent un profil large : 2 ans de sciences et de projets, puis une majeure au choix (énergie, mécanique, numérique, aéronautique, santé…). Souvent un semestre à l'étranger et des stages au fil du cursus.",
    apres: "Ingénieur dans l'industrie, le conseil, l'énergie, le numérique ou les transports, selon la majeure choisie.",
    mpc: "Le format école en 5 ans sans fermer de porte : utile si tu veux une école d'ingénieurs sans savoir encore quel domaine. Ton combo convient : le concours Avenir (EPF, ESILV, ECE, EIGSI, ESIGELEC) demande maths + une spécialité scientifique et ne compte que pour un vœu Parcoursup. Compare surtout les frais, les majeures et la place de l'international.",
    w: { MECA: 1, ENER: 1, NUM: .8, MATH: .7, PHYS: .6, ECO: .3 }, kw: ["industrie", "energie", "international", "entreprise"],
    p: { enc: .8, conc: .6, intense: .6, maths: .7, phys: .6, chim: .2, code: .4, ecrit: .2, oral: .4, vente: 0, bureau: .6, terrain: .1, indus: .3, ouvert: .6, gen: 1, integ: 1, sortie: 5, concours: 1, prive: 1 },
    src: { u: "https://www.onisep.fr/ressources/univers-formation/formations/post-bac/diplome-d-ingenieur-de-l-epf", l: "Fiche Onisep" } },

  { id: "ing_num", nom: "Écoles d'ingénieurs post-bac du numérique et de l'électronique (EPITA, EFREI, ESIEA, ISEP, ESIEE Paris, ISEN…)", duree: "5 ans (prépa intégrée de 2 ans + cycle ingénieur de 3 ans)", sel: 2, selNote: "Concours Advance (EPITA : QCM et entretien) ou Puissance Alpha (EFREI, ESIEA, ISEP, ESIEE Paris, ISEN : dossier et QCM)", cout: "Environ 7 000 à 13 000 € par an selon l'école et l'année (gratuit en apprentissage, souvent à partir de la 3e année)", alt: .5, inge: 1,
    core: ["dev", "ia", "electronique", "robot"],
    alias: ["EPITA", "EFREI", "ESIEA", "ISEP", "ISEN", "Junia ISEN", "ISEN Méditerranée", "ISEN Ouest", "ESIEE", "ESIEE Paris", "école d'informatique", "école d'ingénieur informatique"],
    desc: "Des écoles privées centrées dès les premières années sur l'informatique, les réseaux, la cybersécurité, l'intelligence artificielle ou l'électronique et les systèmes embarqués, avec beaucoup de projets en équipe.",
    apres: "Ingénieur logiciel, en cybersécurité, en données et IA, en systèmes embarqués ou en réseaux et télécoms.",
    mpc: "Accessible sans NSI : maths + physique-chimie suffisent (la physique sert pour l'électronique, les maths pour l'algorithmique et l'IA), et l'EPITA recommande les maths expertes. Vérifie que l'école délivre bien le titre d'ingénieur reconnu par la CTI (Commission des titres d'ingénieur) : ce n'est pas le cas d'Epitech.",
    w: { NUM: 1, ENER: .5, MATH: .5 }, kw: ["dev", "ia", "electronique", "robot"],
    p: { enc: .7, conc: .7, intense: .6, maths: .6, phys: .4, chim: 0, code: .9, ecrit: .2, oral: .3, vente: 0, bureau: .9, terrain: 0, indus: .1, ouvert: .4, gen: .4, integ: 1, sortie: 5, concours: 1, prive: 1 },
    src: { u: "https://www.onisep.fr/ressources/univers-formation/formations/post-bac/diplome-d-ingenieur-d-efrei-paris", l: "Fiche Onisep" } },

  { id: "ing_btp", nom: "Écoles d'ingénieurs post-bac du bâtiment et des travaux publics (ESITC Paris, ESITC Metz, BUILDERS…)", duree: "5 ans (prépa intégrée de 2 ans + cycle ingénieur de 3 ans)", sel: 2, selNote: "Concours Puissance Alpha (ESITC) ou Avenir (BUILDERS) : dossier et QCM", cout: "Environ 8 400 € par an à l'ESITC Paris (tarif garanti sur toute la durée), variable selon l'école ; gratuit en apprentissage", alt: .5, inge: 1,
    core: ["construction"],
    alias: ["ESITC", "ESITC Paris", "ESITC Metz", "ESITC Caen", "BUILDERS", "ESTP", "école des travaux publics", "BTP", "génie civil", "école de la construction"],
    desc: "Des écoles privées qui forment aux métiers de la construction dès le bac : structures, infrastructures et réseaux, maquette numérique du bâtiment (BIM), construction durable et énergie, avec des stages sur chantier et en bureau d'études.",
    apres: "Ingénieur travaux, ingénieur structure ou méthodes, chef de projet dans le BTP, l'aménagement ou l'énergie.",
    mpc: "Ton combo suffit : l'ESITC Paris conseille les maths et la physique au lycée, et les deux ESITC passent par le concours Puissance Alpha. L'ESTP, elle, ne propose pas de cycle ingénieur direct après le bac : on y entre d'abord en bachelor de 3 ans, puis sur sélection en cycle ingénieur.",
    w: { BAT: 1, MECA: .4, MATH: .3 }, kw: ["construction", "environnement", "industrie"],
    p: { enc: .8, conc: .8, intense: .6, maths: .6, phys: .5, chim: .1, code: .2, ecrit: .2, oral: .3, vente: 0, bureau: .5, terrain: .6, indus: .7, ouvert: .3, gen: .3, integ: 1, sortie: 5, concours: 1, prive: 1 },
    src: { u: "https://www.esitc-paris.fr/fr/admissions/formation-ingenieur-admission-post-bac", l: "ESITC Paris" } },

  { id: "ing_chimie", nom: "Écoles d'ingénieurs post-bac en chimie et biotechnologies (ESCOM, CPE Lyon, Sup'Biotech, EBI…)", duree: "5 ans (prépa intégrée de 2 ans + cycle ingénieur de 3 ans)", sel: 2, selNote: "Concours Puissance Alpha (ESCOM, CPE Lyon), Advance (Sup'Biotech) ou Avenir (EBI, dès 2027)", cout: "Très variable : ESCOM 4 500 € par an en prépa puis 7 750 €, Sup'Biotech environ 9 900 à 12 600 € ; gratuit en apprentissage", alt: .3, inge: 1,
    core: ["chimie", "sante", "biomed", "agro"],
    alias: ["ESCOM", "ESCOM Chimie", "CPE Lyon", "Sup'Biotech", "SupBiotech", "EBI", "école de biologie industrielle", "biotechnologies", "école de chimie"],
    desc: "Des écoles privées qui recrutent après le bac pour la chimie et le génie des procédés (ESCOM, CPE Lyon) ou les biotechnologies et bio-industries (Sup'Biotech, EBI), avec beaucoup de laboratoire.",
    apres: "Ingénieur en pharmacie, cosmétique, agroalimentaire, chimie fine, environnement ou matériaux.",
    mpc: "Si la chimie est ce que tu préfères en physique-chimie : l'ESCOM accepte toute spécialité scientifique, donc ton combo convient. Pour les biotechnologies, Sup'Biotech cite maths + physique-chimie parmi les combinaisons attendues, mais prévois de remettre la biologie à niveau.",
    w: { CHIM: 1, VIE: .6, PHYS: .3 }, kw: ["chimie", "sante", "agro", "environnement"],
    p: { enc: .8, conc: .6, intense: .6, maths: .5, phys: .5, chim: .9, code: .1, ecrit: .2, oral: .3, vente: 0, bureau: .4, terrain: 0, indus: .6, ouvert: .3, gen: .3, integ: 1, sortie: 5, concours: 1, prive: 1 },
    src: { u: "https://www.escom.fr/formation/admissions-classes-preparatoires/", l: "ESCOM" } },

  { id: "ing_agro", nom: "Écoles d'ingénieurs post-bac en agronomie et environnement (UniLaSalle, ISA Junia, ESA, Purpan…)", duree: "5 ans (2 + 3 ans ou 3 + 2 ans selon l'école)", sel: 2, selNote: "Dossier et entretien de motivation sur Parcoursup, sans concours écrit", cout: "Environ 5 500 à 9 500 € par an selon l'école et l'année (ESA : environ 7 600 à 8 100 €) ; gratuit en apprentissage, possible dès la 3e année", alt: .3, inge: 1,
    core: ["agro", "environnement"],
    alias: ["UniLaSalle", "ISA", "ISA Lille", "Junia ISA", "ESA Angers", "Purpan", "ISARA", "France Agro3", "école d'agro", "agronomie", "école d'agronomie"],
    desc: "Des écoles privées qui forment après le bac aux métiers de l'agriculture, de l'alimentation, de l'environnement et du paysage (et, à UniLaSalle, aux géosciences et à l'énergie), avec des stages en exploitation et en entreprise.",
    apres: "Ingénieur agronome, en agroalimentaire, en environnement, en conseil agricole ou en développement durable.",
    mpc: "La SVT n'est pas exigée : l'ESA demande au moins une spécialité scientifique (maths très recommandées) et Purpan conseille de garder une matière scientifique. Avec maths + physique-chimie tu es dans les profils attendus ; l'entretien de motivation est le moment de montrer ton intérêt pour le vivant et le terrain.",
    w: { VIE: 1, CHIM: .4, ECO: .3 }, kw: ["agro", "environnement", "entreprise"],
    p: { enc: .8, conc: .8, intense: .5, maths: .4, phys: .3, chim: .5, code: .1, ecrit: .3, oral: .4, vente: .1, bureau: .4, terrain: .7, indus: .3, ouvert: .3, gen: .4, integ: 1, sortie: 5, concours: .5, prive: 1 },
    src: { u: "https://www.onisep.fr/ressources/univers-formation/formations/post-bac/diplome-d-ingenieur-de-l-institut-superieur-d-agriculture-junia", l: "Fiche Onisep" } },

  { id: "ing_app", nom: "Écoles d'ingénieurs post-bac tournées vers l'apprentissage (CESI, Icam…)", duree: "5 ans, dont 3 possibles en apprentissage", sel: 2, selNote: "Sélection sur dossier et entretien ou oral, sans concours écrit", cout: "Payant pendant la prépa intégrée (CESI : 6 500 € par an), puis gratuit et rémunéré en apprentissage ; en statut étudiant, le cycle ingénieur coûte environ 8 500 à 9 900 € par an", alt: .9, inge: 1,
    alias: ["CESI", "CESI Ingénieurs", "Icam", "ingénieur en apprentissage", "alternance ingénieur", "école d'ingénieurs en alternance"],
    desc: "Une prépa intégrée de 2 ans, puis un cycle ingénieur de 3 ans où tu peux être apprenti : tu alternes école et entreprise, avec un salaire et une formation payée par l'entreprise. Pédagogies actives et expérience d'entreprise tout au long du cursus.",
    apres: "Ingénieur dans l'industrie, le numérique, le BTP ou la qualité-sécurité-environnement, avec plusieurs années d'expérience en entreprise dès le diplôme si tu as fait le cycle ingénieur en apprentissage.",
    mpc: "Pour qui veut du concret et une première expérience pro dès 20 ans : ton combo convient (CESI : bac général scientifique ; Icam : maths + une spécialité scientifique), avec une sélection sur dossier et oral. Pour l'apprentissage en 3e année, il faudra signer un contrat avec une entreprise : commence à chercher tôt.",
    w: { MECA: .8, ENER: .7, NUM: .6, BAT: .5, ECO: .5 }, kw: ["industrie", "entreprise", "construction", "dev"],
    p: { enc: .7, conc: .9, intense: .6, maths: .5, phys: .4, chim: .1, code: .3, ecrit: .2, oral: .4, vente: 0, bureau: .5, terrain: .4, indus: .6, ouvert: .5, gen: .7, integ: 1, sortie: 5, concours: .5, prive: 1 },
    src: { u: "https://www.cesi.fr/programmes/cursus-ingenieur-5-ans/", l: "CESI" } }
]);
