// Écoles d'ingénieurs publiques qui recrutent après le bac. Faits vérifiés en octobre 2026 : voir dev/facts_prepa_ingpub.md.
add("ingpub", [
  { id: "insa", nom: "Groupe INSA (instituts nationaux des sciences appliquées)", duree: "5 ans (2 ans de premier cycle + 3 ans de spécialité)", sel: 3, selNote: "Très demandé : dossier, puis entretien obligatoire (frais de dossier d'environ 105 € en 2026, gratuit si boursier)", cout: ING_PUB_COST, alt: .3, inge: 1,
    alias: ["INSA", "INSA Lyon", "INSA Toulouse", "INSA Rennes", "INSA Rouen", "INSA Rouen Normandie", "INSA Strasbourg", "INSA Hauts-de-France", "INSA Valenciennes", "INSA Centre Val de Loire", "INSA Blois", "Groupe INSA", "procédure INSA"],
    desc: "Sept écoles publiques d'ingénieurs (Lyon, Toulouse, Rennes, Rouen, Strasbourg, Hauts-de-France, Centre Val de Loire) qui recrutent dès le bac : 2 ans de premier cycle scientifique (maths, physique, informatique…), puis 3 ans de spécialité (mécanique, génie civil, informatique, énergie, matériaux…) choisie selon tes résultats et tes vœux.",
    apres: "Ingénieur dans presque tous les secteurs. Plusieurs INSA proposent des parcours aménagés pour les sportifs et les artistes de haut niveau, ainsi que des parcours internationaux.",
    mpc: "Le profil type : maths et physique-chimie (plus de 8 admis sur 10 en 2025). Une des grandes routes publiques et peu chères vers le diplôme d'ingénieur, sans prépa classique ni concours écrit : le dossier et un entretien de motivation décident.",
    w: { MATH: 1, PHYS: .9, MECA: .8, ENER: .8, NUM: .7, BAT: .5 }, kw: ["industrie", "energie", "construction", "international"],
    p: { enc: .8, conc: .5, intense: .8, maths: .8, phys: .7, chim: .3, code: .4, ecrit: .2, oral: .3, vente: 0, bureau: .6, terrain: .1, indus: .3, ouvert: .7, gen: 1, integ: 1, sortie: 5, concours: .5 },
    src: { u: "https://groupe-insa.fr/", l: "Groupe INSA" } },

  { id: "ut", nom: "Universités de technologie (UTC Compiègne, UTT Troyes, UTBM Belfort-Montbéliard)", duree: "5 ans (tronc commun de 2 ans + branche ingénieur de 3 ans)", sel: 2, selNote: "Dossier via Parcoursup, puis entretien de motivation en visioconférence (105 € de frais en 2026, gratuit si boursier)", cout: ING_PUB_COST, alt: .3, inge: 1,
    alias: ["UTC", "UTT", "UTBM", "Groupe UT", "université de technologie", "Compiègne", "Troyes", "Belfort", "Montbéliard"],
    desc: "Trois écoles publiques d'ingénieurs qui recrutent après le bac, avec un fonctionnement plus souple qu'une école classique : tu composes en partie ton parcours en choisissant tes cours, avec beaucoup de projets et plusieurs stages en entreprise (jusqu'à 56 semaines en tout à l'UTT).",
    apres: "Ingénieur en mécanique, informatique, génie industriel, génie biologique, génie des procédés, énergie, matériaux… selon la branche choisie après le tronc commun. Certaines branches existent aussi en apprentissage.",
    mpc: "Une route publique et peu chère vers le diplôme d'ingénieur, pour qui aime construire son parcours et travailler en projets. Il faut être autonome : personne ne fait ton emploi du temps à ta place.",
    w: { MECA: 1, NUM: .8, ENER: .7, MATH: .7, CHIM: .4, VIE: .3 }, kw: ["industrie", "biomed", "energie", "international"],
    p: { enc: .5, conc: .7, intense: .7, maths: .7, phys: .6, chim: .3, code: .4, ecrit: .2, oral: .4, vente: 0, bureau: .6, terrain: .1, indus: .3, ouvert: .7, gen: .9, integ: 1, sortie: 5, concours: .5 },
    src: { u: "https://www.groupe-ut.fr/informations-pratiques/", l: "Groupe UT" } },

  { id: "polytech", nom: "Réseau Polytech, parcours PeiP (parcours des écoles d'ingénieurs Polytech)", duree: "5 ans (2 ans de PeiP + 3 ans de cycle ingénieur)", sel: 2, selNote: "Concours Geipi Polytech via Parcoursup : dossier et épreuve écrite de 3 h, sans entretien en bac général (60 € de frais en 2026, gratuit si boursier)", cout: ING_PUB_COST, alt: .4, inge: 1,
    alias: ["Polytech", "PeiP", "Geipi", "Geipi Polytech", "école universitaire d'ingénieurs"],
    desc: "Seize écoles publiques d'ingénieurs rattachées à des universités, dans toute la France. Le PeiP, avec des cours de maths, de physique-chimie et d'informatique, dure 2 ans : si tu le valides, tu accèdes au cycle ingénieur d'une école du réseau selon ton classement et tes vœux, sans nouveau concours.",
    apres: "Ingénieur en informatique, mécanique, électronique, matériaux, génie biologique, eau et environnement… selon l'école et la spécialité choisies à la fin du PeiP. Le réseau propose aussi aux diplômés du PeiP de faire le cycle ingénieur en apprentissage.",
    mpc: "Ton profil est adapté : en 2026, l'écrit du concours comprenait un QCM de maths et 2 sujets au choix, dont maths et physique-chimie. Tu peux changer d'école pour le cycle ingénieur, mais il faut valider les 2 années de PeiP.",
    w: { MECA: 1, MATH: .8, PHYS: .8, ENER: .8, NUM: .8, VIE: .4 }, kw: ["industrie", "environnement", "electronique", "energie"],
    p: { enc: .7, conc: .5, intense: .6, maths: .7, phys: .7, chim: .3, code: .4, ecrit: .2, oral: .3, vente: 0, bureau: .6, terrain: .1, indus: .3, ouvert: .7, gen: .9, integ: 1, sortie: 5, concours: 1, fac: .5 },
    src: { u: "https://www.polytech-reseau.org/cycle-preparatoire-peip/", l: "Réseau Polytech" } },

  { id: "prepa_inp", nom: "La Prépa des INP (prépa intégrée des instituts nationaux polytechniques)", duree: "2 ans de prépa, puis 3 ans dans une école du groupe INP", sel: 2, selNote: "Sur dossier via Parcoursup, puis entretien de motivation (environ 420 places sur 10 sites en 2025)", cout: ING_PUB_COST, alt: 0, inge: 1,
    alias: ["Prépa des INP", "CPP", "INP", "Groupe INP", "Grenoble INP", "Toulouse INP", "Bordeaux INP", "Clermont Auvergne INP", "Lorraine INP", "ENSEEIHT", "ENSIACET"],
    desc: "Une prépa publique en 2 ans, sans concours à la fin : tu rejoins une école d'ingénieurs du groupe INP selon ton classement au contrôle continu et tes vœux. Dix sites : Bordeaux, Cambrai, Clermont-Ferrand, Grenoble, Nancy, Quimper, Toulouse, Valence, Pointe-à-Pitre et Saint-Denis de La Réunion.",
    apres: "Plus de trente écoles d'ingénieurs publiques réparties dans les INP (Grenoble INP, Toulouse INP, Bordeaux INP…) : électronique, informatique, énergie, chimie, mécanique, matériaux, agronomie… Selon Grenoble INP, plus de 9 élèves sur 10 obtiennent l'une de leurs trois premières écoles souhaitées.",
    mpc: "Maths + physique-chimie est un profil adapté. Le dossier (notes de première et de terminale) et un entretien de motivation décident : une bonne voie si tu veux une école publique du groupe INP sans passer de concours.",
    w: { MATH: .9, PHYS: .9, ENER: .7, CHIM: .7, NUM: .6, MECA: .6 }, kw: ["energie", "chimie", "electronique", "industrie"],
    p: { enc: .9, conc: .3, intense: .8, maths: .9, phys: .8, chim: .5, code: .3, ecrit: .2, oral: .4, vente: 0, bureau: .8, terrain: 0, indus: .1, ouvert: .8, gen: 1, integ: .7, sortie: 5, concours: .5 },
    src: { u: "https://www.groupe-inp.fr/la-prepa-des-inp", l: "Groupe INP" } },

  { id: "cpi_chimie", nom: "Prépas intégrées de chimie (CPI, cycles préparatoires intégrés de la Fédération Gay-Lussac)", duree: "2 ans de prépa, puis 3 ans dans une école de chimie", sel: 2, selNote: "Un seul dossier Parcoursup et un seul entretien pour les 5 centres (frais de candidature de 95 € en 2026, 50 € si boursier)", cout: "Environ 735 €/an pendant les 2 ans de CPI (630 € de droits d'inscription + 105 € de CVEC, 0 € si boursier) ; frais plus élevés ensuite si tu choisis une école privée du réseau", alt: 0, inge: 1,
    core: ["chimie"],
    alias: ["CPI", "Gay-Lussac", "Fédération Gay-Lussac", "20 écoles de chimie", "école de chimie", "ENSCR", "ENSCL", "ECPM", "ENSGTI", "SIGMA Clermont", "CPE Lyon", "Chimie ParisTech"],
    desc: "Une prépa de 2 ans centrée sur la chimie et le génie des procédés, avec des TP (travaux pratiques), dans 5 centres : Clermont-Ferrand, Lille, Pau, Rennes et Strasbourg. Pas de concours à la fin : un classement commun répartit les élèves entre les 20 écoles d'ingénieurs de la Fédération Gay-Lussac.",
    apres: "Ingénieur chimiste ou en génie des procédés : pharmacie, cosmétique, énergie, matériaux, environnement, agroalimentaire. Les 20 écoles de la Fédération sont publiques ou privées.",
    mpc: "Si la chimie est ta partie préférée de physique-chimie, c'est un prolongement naturel : les maths et la physique restent au programme, avec la chimie au centre. Si tu ne veux pas d'école privée, classe-les en dernier au moment de tes vœux d'école.",
    w: { CHIM: 1, PHYS: .5, MATH: .4 }, kw: ["chimie", "industrie", "environnement", "sante"],
    p: { enc: .9, conc: .5, intense: .8, maths: .6, phys: .6, chim: 1, code: .1, ecrit: .2, oral: .3, vente: 0, bureau: .4, terrain: 0, indus: .5, ouvert: .4, gen: .3, integ: .8, sortie: 5, concours: .5 },
    src: { u: "https://20ecolesdechimie.com/", l: "Fédération Gay-Lussac" } },

  { id: "ingpub_autres", nom: "Autres écoles publiques d'ingénieurs recrutant après le bac (concours Geipi Polytech)", duree: "5 ans (prépa intégrée + cycle ingénieur)", sel: 2, selNote: "Dossier, puis épreuve écrite de 3 h (concours Geipi Polytech)", cout: "Environ 735 €/an dans la plupart des écoles (630 € de droits d'inscription + 105 € de CVEC, 0 € si boursier) ; plus élevé dans quelques écoles sous une autre tutelle (IMT Nord Europe : environ 3 200 €/an en 2025)", alt: .3, side: true, inge: 1,
    alias: ["Geipi", "Geipi Polytech", "ENIB", "ENIM", "ENIT", "ENISE", "ENSIM", "ENSIBS", "ESIR", "ISAT", "ISEL", "ISTY", "EEIGM", "Sup Galilée", "ESIROI", "ESGT", "Esisar", "Bretagne INP", "IMT Nord Europe", "Télécom Saint-Étienne"],
    desc: "Une vingtaine d'autres écoles publiques recrutent dès le bac par le concours Geipi Polytech : des écoles d'ingénieurs comme l'ENIB (Brest), l'ENSIM (Le Mans), l'ESIR (Rennes) ou Sup Galilée (Sorbonne Paris Nord), et des écoles plus spécialisées comme l'ISAT (automobile et transports, à Nevers) ou l'EEIGM (génie des matériaux, à Nancy).",
    apres: "Ingénieur dans la spécialité de l'école (mécanique, informatique, électronique, matériaux, logistique…) ; certaines écoles proposent aussi le cycle ingénieur en apprentissage.",
    mpc: "Même concours que Polytech : un seul vœu Parcoursup te permet de viser plusieurs de ces écoles. À regarder si tu sais déjà quel domaine te plaît, car chaque école est assez spécialisée.",
    w: { MECA: 1, ENER: .7, PHYS: .6, MATH: .6, CHIM: .4 }, kw: ["industrie", "auto", "energie", "electronique"],
    p: { enc: .8, conc: .6, intense: .6, maths: .7, phys: .7, chim: .3, code: .3, ecrit: .2, oral: .3, vente: 0, bureau: .6, terrain: .1, indus: .4, ouvert: .5, gen: .5, integ: 1, sortie: 5, concours: 1 },
    src: { u: "https://www.geipi-polytech.org/ecoles/", l: "Concours Geipi Polytech" } },

  { id: "bachelor_am", nom: "Bachelor en sciences et ingénierie Arts et Métiers (BSI, génie mécanique et production)", duree: "3 ans (grade de licence)", sel: 2, selNote: "Parcoursup : dossier, puis entretien de motivation", cout: "Environ 283 €/an en statut étudiant (178 € de droits d'inscription au tarif licence + 105 € de CVEC, 0 € si boursier) ; la 3e année se fait en alternance", alt: .5, side: true, inge: .5,
    alias: ["Arts et Métiers", "ENSAM", "bachelor Arts et Métiers", "BSI", "bachelor de technologie", "Bordeaux-Talence", "Châlons-en-Champagne"],
    desc: "Un bachelor en 3 ans de génie mécanique et production, sur les campus Arts et Métiers de Bordeaux-Talence et de Châlons-en-Champagne. La 3e année se fait en alternance. Il est accessible en majorité aux bacheliers du bac technologique STI2D et à quelques bacheliers généraux.",
    apres: "Assistant ingénieur en production, technicien de bureau d'études, coordinateur de maintenance, technicien contrôle qualité ; ou poursuite en master ou en cursus d'ingénieur (dont celui d'Arts et Métiers, avec un concours spécifique).",
    mpc: "Maths + physique-chimie est un profil accepté, mais la formation est pensée d'abord pour les bacheliers STI2D : tu seras en minorité. Une route concrète vers l'industrie en 3 ans, plutôt qu'un chemin direct vers le titre d'ingénieur.",
    w: { MECA: 1, ENER: .5, MATH: .3 }, kw: ["industrie", "auto", "robot"],
    p: { enc: .9, conc: .9, intense: .5, maths: .5, phys: .5, chim: .1, code: .3, ecrit: .2, oral: .3, vente: 0, bureau: .4, terrain: .1, indus: .8, ouvert: .5, gen: .5, integ: .3, sortie: 3, concours: .5 },
    src: { u: "https://www.onisep.fr/ressources/univers-formation/formations/post-bac/bachelor-en-sciences-et-ingenierie-genie-mecanique-et-production-ensam", l: "Fiche Onisep" } }
]);
