// Autres voies : commerce, informatique, armées, pilote, marine marchande, météo, études à l'étranger, bachelor, IEP, césure. Vérifié le 5 octobre 2026 (voir dev/facts_autre.md).
add("autre", [
  { id: "commerce", nom: "Écoles de commerce post-bac", duree: "3 à 5 ans", sel: 2, cout: "Souvent 8 000 à 15 000 €/an, parfois plus", alt: .6, side: true, inge: 0,
    core: ["entreprise", "finance", "international"],
    alias: ["école de commerce", "business school", "bachelor commerce", "concours Accès", "concours Sésame"],
    desc: "Bachelors en 3 ou 4 ans, ou programmes en 4 à 5 ans, recrutés via des concours communs sur Parcoursup (Sésame, Accès, Ecricome Bachelor, Pass…), avec des frais d'inscription au concours.",
    apres: "Marketing, finance, commerce, management, souvent à l'international.",
    mpc: "Ton niveau en maths est un atout aux concours, mais le cœur, c'est la gestion, le marketing et les langues : la physique n'y sert plus. Vérifie les labels (visa, grade de licence ou de master).",
    w: { ECO: 1, HUM: .2 }, kw: ["entreprise", "finance", "international"],
    p: { enc: .7, conc: .6, intense: .5, maths: .3, phys: 0, chim: 0, code: .1, ecrit: .4, oral: .8, vente: .5, bureau: .7, terrain: .2, indus: 0, ouvert: .5, gen: .7, integ: 1, sortie: 3, concours: 1, prive: 1 },
    src: { u: "https://www.onisep.fr/formation/les-principaux-domaines-de-formation/les-ecoles-de-commerce", l: "Onisep" } },

  { id: "info_hors_inge", nom: "Écoles d'informatique sans titre d'ingénieur (Epitech, 42…)", duree: "Epitech : 5 ans ; 42 : 3 à 5 ans selon ton rythme", sel: 2, cout: "Epitech : de 8 270 à 10 560 €/an selon l'année (2026-2027), plus 990 € d'inscription ; 42 : gratuit", alt: .3, inge: 0,
    core: ["dev", "ia"],
    alias: ["Epitech", "42", "école 42", "école d'informatique", "piscine 42"],
    desc: "Une pédagogie par projets, sans cours magistraux : tu apprends à coder en réalisant des projets, seul ou en équipe. Epitech recrute sur Parcoursup (tests et entretien de motivation) ; à 42, l'entrée se fait par une « piscine », un mois de sélection intensive.",
    apres: "Développeur, ingénieur logiciel, expert en cybersécurité. Epitech délivre un diplôme bac+5 visé par l'État, 42 des titres inscrits au RNCP (répertoire des certifications professionnelles) : ce ne sont pas des titres d'ingénieur.",
    mpc: "Pour qui veut coder dès le premier jour et apprend mieux en faisant. Aucune spécialité n'est exigée et les maths ou la physique y servent peu : vérifie que c'est bien ce que tu veux.",
    w: { NUM: 1 }, kw: ["dev", "ia"],
    p: { enc: .2, conc: 1, intense: .7, maths: .3, phys: 0, chim: 0, code: 1, ecrit: .1, oral: .3, vente: 0, bureau: 1, terrain: 0, indus: 0, ouvert: .4, gen: .3, integ: 1, sortie: 5, concours: .5 },
    src: { u: "https://www.epitech.eu/programme-grande-ecole-informatique/", l: "Epitech" } },

  { id: "armees_off", nom: "Armées : écoles d'officiers (École de l'air et de l'espace, École navale, Saint-Cyr, Polytechnique)", duree: "Prépa scientifique (2 ans), puis 3 ans d'école (4 ans à Polytechnique)", sel: 3, cout: "Formation rémunérée ; à Polytechnique, engagement de 10 ans au service de l'État, sinon remboursement", alt: 0, side: true, inge: 1,
    core: ["defense", "pilote", "aero"],
    alias: ["École de l'air", "École de l'air et de l'espace", "École navale", "Saint-Cyr", "École spéciale militaire", "officier", "armée de l'air", "Marine nationale"],
    desc: "Ces écoles (École de l'air et de l'espace, École navale, École spéciale militaire de Saint-Cyr pour l'armée de terre, Polytechnique) recrutent surtout après une prépa scientifique, sur concours : tu deviens ingénieur et officier, avec un statut militaire et une solde. Des lycées militaires ont leurs propres prépas.",
    apres: "Officier de l'armée de l'air et de l'espace (pilote, ingénieur, contrôleur), de la marine ou de l'armée de terre ; à Polytechnique, carrière d'ingénieur dans tous les secteurs, après un engagement de service à l'État.",
    mpc: "Avec maths + physique-chimie, la route passe par une prépa scientifique (MPSI, PCSI ou MP2I, puis MP, MPI, PC ou PSI) et le concours, avec aptitude médicale et sportive exigée. Avec le bac seul, il n'existe que des postes d'officier pilote ou navigant sous contrat (armée de l'air, armée de terre), sans titre d'ingénieur.",
    w: { MECA: .7, HUM: .6, MATH: .5, PHYS: .5 }, kw: ["defense", "pilote", "aero"],
    p: { enc: 1, conc: .6, intense: 1, maths: .8, phys: .7, chim: .2, code: .2, ecrit: .3, oral: .5, vente: 0, bureau: .4, terrain: .8, indus: .3, ouvert: .4, gen: .6, integ: 0, sortie: 5, concours: 1, prepa: 1 },
    src: { u: "https://www.onisep.fr/formation/les-principaux-domaines-de-formation/les-ecoles-de-la-defense", l: "Onisep" } },

  { id: "armees_sof", nom: "Armées : sous-officiers techniciens (recrutement après le bac)", duree: "Formation militaire de 4 à 8 mois, puis formation de spécialité de quelques semaines à 9 mois, payée", sel: 2, cout: "Formation rémunérée", alt: 0, side: true, inge: 0,
    core: ["defense", "aero", "pilote"],
    alias: ["sous-officier", "armée", "militaire", "école de maistrance", "maistrance", "officier marinier", "ENSOA", "Rochefort"],
    desc: "Avec le bac, l'armée de l'air et de l'espace, la marine (école de maistrance, à Brest ou Saint-Mandrier) et l'armée de terre recrutent des sous-officiers techniciens : maintenance d'avions ou de navires, électronique, radars, systèmes d'information… Sélection sur tests, entretien et aptitude physique ; limite d'âge de 30 à 32 ans selon l'armée.",
    apres: "Technicien militaire (un sergent de l'armée de terre gagne 2 134 € brut par mois après un an en régiment), avec des possibilités d'évoluer (concours internes, officier) et des qualifications reconnues dans le civil.",
    mpc: "Ton profil scientifique ouvre les spécialités les plus techniques. Il faut accepter le cadre militaire, la mobilité et un engagement de plusieurs années (10 ans à l'école de maistrance de la marine).",
    w: { MECA: .8, ENER: .6, HUM: .5 }, kw: ["defense", "aero", "electronique"],
    p: { enc: 1, conc: 1, intense: .7, maths: .3, phys: .4, chim: 0, code: .2, ecrit: .2, oral: .3, vente: 0, bureau: .2, terrain: .9, indus: .7, ouvert: .3, gen: .3, integ: 0, sortie: 1, concours: 1 },
    src: { u: "https://www.onisep.fr/formation/les-principaux-domaines-de-formation/les-ecoles-de-la-defense", l: "Onisep" } },

  { id: "pilote", nom: "Pilote de ligne (ENAC, Cadets d'Air France, écoles privées)", duree: "Environ 2 ans de formation de pilote, en général après un an d'études scientifiques", sel: 3, cout: "ENAC : 190 € de frais de concours, puis 1 500 €/an de scolarité d'après la notice 2026 (vols pris en charge par l'école) ; Cadets d'Air France : formation financée par la compagnie ; école privée : souvent 70 000 à 120 000 €", alt: 0, side: true, inge: 0,
    core: ["pilote"],
    alias: ["pilote", "pilote de ligne", "ENAC", "cadets Air France", "Air France", "EPL", "ATPL", "aviation"],
    desc: "Il faut décrocher la licence ATPL (pilote de ligne). L'ENAC, École nationale de l'aviation civile, recrute sur concours (maths, physique, anglais, tests psychotechniques) à partir de 60 crédits ECTS, soit un an d'études scientifiques. Air France recrute aussi des Cadets, et les écoles privées prennent dès le bac mais coûtent très cher.",
    apres: "Copilote puis commandant de bord en compagnie aérienne ; l'emploi suit les cycles du transport aérien. L'ENAC délivre un diplôme de niveau bac+3 (grade de licence).",
    mpc: "Les concours reposent beaucoup sur les maths, la physique et l'anglais : ton profil est le bon. À l'ENAC, il faut d'abord un an d'études scientifiques, sauf un cycle préparatoire de 10 mois réservé à quelques élèves de terminale boursiers (5 places en 2026) ; vérifie tôt l'aptitude médicale de classe 1, obligatoire.",
    w: { MECA: 1, HUM: .4, PHYS: .3 }, kw: ["pilote", "aero", "international"],
    p: { enc: 1, conc: 1, intense: .9, maths: .5, phys: .5, chim: 0, code: 0, ecrit: .1, oral: .4, vente: 0, bureau: .1, terrain: .9, indus: .2, ouvert: .1, gen: .1, integ: 1, sortie: 3, niv: 2, concours: 1 },
    src: { u: "https://www.onisep.fr/ressources/univers-formation/formations/post-bac/pilote-de-ligne-enac", l: "Fiche Onisep" } },

  { id: "marine_marchande", nom: "Marine marchande : officier à l'École nationale supérieure maritime (ENSM)", duree: "5 ans (ingénieur, grade de master) ou 3 ans (officier, grade de licence), avec de longues périodes en mer", sel: 2, selNote: "Pas de concours : sélection sur Parcoursup (dossier, lettre de motivation, oral pour le cursus d'ingénieur)", cout: "Environ 1 600 €/an (montant 2025-2026), boursiers exonérés ; pas de logement sur les campus", alt: .2, side: true, inge: 1,
    core: ["transport"],
    alias: ["ENSM", "École nationale supérieure maritime", "marine marchande", "officier de la marine marchande", "officier polyvalent", "ingénieur navigant", "capitaine de navire"],
    desc: "L'ENSM forme les officiers qui commandent les navires de commerce et dirigent leurs machines : navigation, énergie, sécurité, longues périodes en mer. Cursus d'ingénieur en 5 ans (diplôme accrédité par la CTI, Commission des titres d'ingénieur) ou d'officier en 3 ans, sur quatre sites : Le Havre, Marseille, Nantes, Saint-Malo.",
    apres: "Officier pont ou machine, puis commandant ou chef mécanicien ; le cursus de génie maritime, sans navigation à bord, mène à des métiers d'ingénieur à terre (gestion du navire, systèmes offshore).",
    mpc: "Le recrutement se fait sur Parcoursup, sans concours : tes résultats en maths et en physique-chimie comptent, et l'école recommande un bac à dominante scientifique, ce qui est ton cas. L'aptitude médicale à la navigation est exigée avant l'entrée : vérifie-la tôt.",
    w: { MECA: .9, ENER: .7, HUM: .3 }, kw: ["transport", "international", "energie"],
    p: { enc: .9, conc: .9, intense: .7, maths: .6, phys: .7, chim: .1, code: .1, ecrit: .2, oral: .3, vente: 0, bureau: .2, terrain: 1, indus: .7, ouvert: .3, gen: .4, integ: 1, sortie: 5, concours: .5 },
    src: { u: "https://www.onisep.fr/ressources/univers-formation/formations/post-bac/diplome-d-ingenieur-de-l-ecole-nationale-superieure-maritime", l: "Fiche Onisep" } },

  { id: "meteo", nom: "Météo et climat (École nationale de la météorologie, masters de sciences de l'atmosphère…)", duree: "Technicien : 2 ans après le bac ; ingénieur : prépa puis 3 ans ; ou licence puis master", sel: 3, cout: "Élèves fonctionnaires rémunérés, avec un engagement de 8 ans pour les ingénieurs ; élèves civils : 618 € en 2024-2025 ; université : tarif public", alt: 0, side: true, inge: .5,
    core: ["environnement", "recherche"],
    alias: ["météo", "météorologie", "météorologue", "climatologue", "Météo-France", "ENM", "École nationale de la météorologie", "ingénieur météo", "technicien météo", "prévisionniste"],
    desc: "Prévoir le temps et comprendre le climat : physique de l'atmosphère, mécanique des fluides, modélisation numérique, observation. L'École nationale de la météorologie (ENM), à Toulouse, forme des techniciens et des ingénieurs, dont ceux de Météo-France.",
    apres: "Prévisionniste, météorologiste-conseil, ingénieur ou chercheur en météo et climat, à Météo-France, dans la recherche ou dans le privé.",
    mpc: "La physique et les maths sont au cœur de la météo. Les techniciens se recrutent par concours au niveau bac scientifique (2 ans de formation, rémunérés), les ingénieurs après une prépa MP, PC, PSI ou MPI (concours Mines-Télécom), et la recherche passe par une licence de physique puis un master de sciences de l'atmosphère.",
    w: { PHYS: 1, VIE: .6, MATH: .6, NUM: .3 }, kw: ["environnement", "recherche", "ia"],
    p: { enc: .7, conc: .5, intense: .7, maths: .8, phys: 1, chim: .2, code: .5, ecrit: .2, oral: .2, vente: 0, bureau: .7, terrain: .3, indus: 0, ouvert: .4, gen: .3, integ: 0, sortie: 3, concours: 1 },
    src: { u: "https://www.onisep.fr/ressources/univers-formation/formations/post-bac/diplome-d-ingenieur-de-l-ecole-nationale-de-la-meteorologie", l: "Fiche Onisep" } },

  { id: "etranger", nom: "Études scientifiques à l'étranger (EPFL et ETH Zurich en Suisse, Belgique, Québec…)", duree: "Bachelor de 3 ans, puis master de 2 ans (plus une année préparatoire intégrée à Polytechnique Montréal)", sel: 2, selNote: "Très variable : examen d'admission en Belgique, environ 16/20 de moyenne à l'EPFL, 13/20 à Polytechnique Montréal", cout: "Belgique : jusqu'à 1 194 €/an ; Suisse : environ 4 500 CHF/an (frais triplés depuis 2025 pour les étrangers non résidents) ; Québec : environ 10 700 $ CAD/an pour un Français ; le coût de la vie s'ajoute", alt: 0, inge: .5,
    core: ["international"],
    alias: ["EPFL", "École polytechnique fédérale de Lausanne", "ETH", "ETH Zurich", "Belgique", "UCLouvain", "Louvain", "Québec", "Canada", "Montréal", "Polytechnique Montréal", "Suisse", "Lausanne", "Zurich", "étranger"],
    desc: "Des universités réputées accueillent des bacheliers français sous conditions : EPFL (École polytechnique fédérale de Lausanne) et ETH Zurich (polytechnique fédérale de Zurich, cours en allemand), facultés polytechniques belges (examen d'admission en ingénieur civil), Polytechnique Montréal. Candidatures hors Parcoursup, souvent dès l'hiver.",
    apres: "Bachelor puis master d'ingénieur ou de sciences à l'étranger ; retour possible en France en master ou en école d'ingénieurs (équivalence à vérifier).",
    mpc: "Maths + physique-chimie correspond à ce que demandent l'EPFL (environ 16/20 en maths, en physique et de moyenne, avec des places limitées) et Polytechnique Montréal (13/20 de moyenne au bac) ; en Belgique, tout se joue à l'examen d'admission. Renseigne-toi tôt sur les dates.",
    w: { MATH: .8, PHYS: .8, ECO: .2 }, kw: ["international", "recherche"],
    p: { enc: .4, conc: .4, intense: .8, maths: .9, phys: .8, chim: .3, code: .3, ecrit: .3, oral: .3, vente: 0, bureau: .8, terrain: 0, indus: 0, ouvert: .8, gen: .8, integ: 0, sortie: 3, concours: .5 },
    src: { u: "https://www.onisep.fr/formation/partir-a-l-etranger/etudier-a-l-etranger-le-tour-du-monde-en-35-pays", l: "Onisep" } },

  { id: "bachelor_sci", nom: "Bachelor scientifique sélectif (Bachelor of Science de l'École polytechnique)", duree: "3 ans", sel: 3, cout: "Environ 15 900 €/an ; exonération pour les boursiers du Crous, bourses d'excellence de 4 800 €/an", alt: 0, side: true, inge: .5, conseil: ["expertes"],
    alias: ["bachelor Polytechnique", "bachelor de l'X", "bachelor of science", "BSc Polytechnique", "Bachelor of Science de l'École polytechnique"],
    desc: "Cursus de 3 ans entièrement en anglais : un tronc commun en première année, puis trois parcours (maths-physique, maths-informatique, maths-économie). Sélection sur dossier et entretien en anglais ; candidature sur le portail de l'école ou sur Parcoursup, une seule fois par an.",
    apres: "Masters en France ou à l'étranger (le diplôme confère le grade de licence), puis recherche ou métiers liés aux maths, à la physique, à l'informatique ou à l'économie.",
    mpc: "Pour un excellent dossier en maths et en physique-chimie, avec un anglais de niveau C1 prouvé par un test ; l'école conseille deux spécialités scientifiques dont maths, si possible avec maths expertes. Les frais sont élevés et l'aide est limitée : candidate tôt si tu en as besoin.",
    w: { MATH: 1, PHYS: .7, NUM: .5, ECO: .3 }, kw: ["recherche", "international", "ia"],
    p: { enc: .6, conc: .3, intense: .9, maths: 1, phys: .7, chim: .1, code: .5, ecrit: .3, oral: .4, vente: 0, bureau: .9, terrain: 0, indus: 0, ouvert: 1, gen: .9, integ: 0, sortie: 3, concours: .5, prive: 1 },
    src: { u: "https://programmes.polytechnique.edu/en/bachelors-admissions/bachelor-of-science/admissions-criteria-and-procedure", l: "École polytechnique" } },

  { id: "iep", nom: "Sciences Po Paris et IEP", duree: "5 ans (grade master)", sel: 3, cout: "Selon les revenus des parents : de 0 à environ 15 000 €/an à Paris, beaucoup moins en région", alt: 0, side: true, inge: 0,
    core: ["societe"],
    alias: ["Sciences Po", "IEP", "science politique"],
    desc: "Science politique, histoire, économie, droit, sociologie et langues, avec une 3e année à l'étranger. Sur Parcoursup : dossier et oral pour Sciences Po Paris ; concours écrit commun le 24 avril 2027 pour 7 IEP ; Bordeaux et Grenoble ont leur propre sélection.",
    apres: "Fonction publique, journalisme, communication, international, conseil, ONG.",
    mpc: "Une vraie ouverture si la société et la politique t'intéressent : les profils scientifiques y sont rares et appréciés, mais il faudra beaucoup lire et écrire.",
    w: { ECO: .7, HUM: .6 }, kw: ["societe", "international"],
    p: { enc: .6, conc: .2, intense: .7, maths: .2, phys: 0, chim: 0, code: 0, ecrit: 1, oral: .8, vente: 0, bureau: .7, terrain: 0, indus: 0, ouvert: .8, gen: .8, integ: 1, sortie: 5, concours: 1 },
    src: { u: "https://www.onisep.fr/formation/les-principaux-domaines-de-formation/les-iep-instituts-d-etudes-politiques", l: "Onisep" } },

  { id: "cesure", nom: "Année de césure", duree: "1 ou 2 semestres", sel: 1, cout: "Droits d'inscription réduits, plus ton projet", alt: 0, inge: 0,
    alias: ["césure", "année de césure", "gap year"],
    desc: "Sur Parcoursup, tu peux demander une césure. Une fois ta place acceptée, tu présentes ton projet (service civique, job, voyage…) à l'établissement, qui peut dire oui ou non. Si c'est oui, une convention te garantit ta place au retour.",
    apres: "Tu reprends dans la formation acceptée, souvent avec des idées plus claires.",
    mpc: "Ce n'est pas une année perdue si elle est construite : un stage dans l'industrie ou un projet à l'étranger peut même t'aider à choisir ta spécialité.",
    w: {}, kw: [],
    p: { enc: .2, conc: 1, intense: .2, ouvert: .8, sortie: 1 },
    src: { u: "https://www.service-public.gouv.fr/particuliers/vosdroits/F33072", l: "Service-public.fr" } }
]);
