// Groupe « bts » : BTS industriels, techniques et voisins pour un profil maths + physique-chimie.
// Rédigé et vérifié début octobre 2026. BTS_COST = "Gratuit en lycée public".
add("bts", [
  { id: "bts_cira", nom: "BTS CIRA (contrôle industriel et régulation automatique)", duree: "2 ans", sel: 1, selNote: "Accessible ; les bacs généraux y sont minoritaires", cout: BTS_COST, alt: .6, inge: .5,
    alias: ["CIRA", "BTS CIRA"],
    core: ["industrie", "robot", "energie", "chimie"],
    desc: "Mesurer et piloter des procédés qui tournent en continu (chimie, pétrochimie, agroalimentaire) : capteurs et instrumentation, régulation automatique d'une température, d'une pression ou d'un débit, automatismes. Physique et chimie industrielles au programme, et 12 semaines de stage.",
    apres: "Technicien en instrumentation, en régulation ou en automatisme dans les industries de procédés. Poursuite possible en licence pro, en 3e année de BUT (selon la spécialité et les places), en prépa ATS (1 an pour viser les écoles d'ingénieurs) ou en école d'ingénieurs par apprentissage.",
    mpc: "Le plus « physique-chimie » des BTS d'automatisme : le CRSA construit des machines, l'électrotechnique s'occupe de l'énergie électrique, le CIRA mesure et régule des fluides et des réactions. Les bacs généraux y sont minoritaires : montre ton goût du concret (stage, visite d'usine, portes ouvertes).",
    w: { ENER: 1, PHYS: .6, CHIM: .5, MATH: .3 }, kw: ["industrie", "robot", "energie", "chimie"],
    p: { enc: 1, conc: .9, intense: .4, maths: .5, phys: .7, chim: .4, code: .3, ecrit: .1, oral: .2, vente: 0, bureau: .3, terrain: .3, indus: .9, ouvert: .4, gen: .3, integ: 0, sortie: 2 },
    src: { u: "https://www.onisep.fr/ressources/univers-formation/formations/post-bac/bts-controle-industriel-et-regulation-automatique", l: "Fiche Onisep" } },

  { id: "bts_elec", nom: "BTS Électrotechnique", duree: "2 ans", sel: 1, selNote: "Accessible ; les bacs généraux y sont rares", cout: BTS_COST, alt: .7, inge: .5,
    alias: ["BTS électrotechnique", "électrotechnique"],
    core: ["energie", "industrie"],
    desc: "L'électricité qui fait tourner les usines, les bâtiments et les transports : distribuer et convertir l'énergie électrique, moteurs et variateurs, installations électriques, bâtiments intelligents. Tu apprends à dimensionner les équipements, à faire plans et schémas, à programmer et à dépanner. 6 à 8 semaines de stage.",
    apres: "Technicien de maintenance, électromécanicien, domoticien ou chef de chantier en électricité (énergie, réseaux, industrie, bâtiment). Poursuite possible en licence pro, en 3e année de BUT (selon la spécialité et les places), en prépa ATS ou en école d'ingénieurs.",
    mpc: "Le BTS de l'énergie électrique : moins de chimie que le CIRA, moins de mécanique que le CRSA, et beaucoup d'électricité appliquée. Très peu de bacs généraux y entrent, mais ta physique est un atout : montre que tu aimes manipuler (montages, projet, stage).",
    w: { ENER: 1, PHYS: .5, BAT: .3, MECA: .2 }, kw: ["energie", "industrie", "construction"],
    p: { enc: 1, conc: .9, intense: .4, maths: .4, phys: .7, chim: .1, code: .3, ecrit: .1, oral: .3, vente: .1, bureau: .3, terrain: .5, indus: .9, ouvert: .4, gen: .4, integ: 0, sortie: 2 },
    src: { u: "https://www.onisep.fr/ressources/univers-formation/formations/post-bac/bts-electrotechnique", l: "Fiche Onisep" } },

  { id: "bts_sn", nom: "BTS CIEL (cybersécurité, informatique et réseaux, électronique), qui remplace le BTS Systèmes numériques", duree: "2 ans", sel: 1, selNote: "Variable selon le lycée et l'option", cout: BTS_COST, alt: .5, inge: .5,
    alias: ["BTS CIEL", "BTS SN", "BTS systèmes numériques"],
    core: ["electronique", "dev", "ia"],
    desc: "Deux options : informatique et réseaux (installer, programmer et sécuriser des systèmes et des réseaux) ou électronique et réseaux (concevoir, prototyper, tester et intégrer des cartes électroniques et des objets connectés). Les deux tiers du temps en enseignement professionnel, et 6 à 8 semaines de stage.",
    apres: "Technicien réseaux et télécoms, administrateur réseaux, informaticien industriel, technicien en électronique (industrie, télécoms, cybersécurité, transports). Poursuite possible en licence (informatique, électronique), en licence pro, en prépa ATS ou en école d'ingénieurs.",
    mpc: "Onisep cite le bac général avec des spécialités scientifiques parmi les accès. La NSI n'est pas exigée : si tu ne l'as pas, montre que tu codes ou bricoles déjà (Arduino, Raspberry Pi, petits programmes).",
    w: { NUM: 1, ENER: .6, PHYS: .2 }, kw: ["electronique", "ia", "dev"],
    p: { enc: 1, conc: .9, intense: .4, maths: .4, phys: .4, chim: 0, code: .7, ecrit: .1, oral: .2, vente: 0, bureau: .7, terrain: .3, indus: .5, ouvert: .5, gen: .4, integ: 0, sortie: 2 },
    src: { u: "https://www.onisep.fr/ressources/univers-formation/formations/post-bac/bts-cybersecurite-informatique-et-reseaux-electronique-option-a-informatique-et-reseaux", l: "Fiche Onisep" } },

  { id: "bts_cpi", nom: "BTS CPI (conception des produits industriels)", duree: "2 ans", sel: 1, cout: BTS_COST, alt: .5, inge: .5,
    alias: ["BTS CPI", "conception des produits industriels"],
    core: ["design", "industrie", "auto"],
    desc: "Concevoir des pièces et des mécanismes en CAO (conception assistée par ordinateur) et en maquette numérique 3D : comparer les solutions, dimensionner, vérifier qu'on saura les fabriquer en tenant compte des coûts, des délais et de la qualité. Un BTS de bureau d'études, avec 6 à 12 semaines de stage.",
    apres: "Dessinateur-projeteur, technicien de bureau d'études ou prototypiste dans tous les secteurs qui fabriquent des produits mécaniques. Plus de la moitié des diplômés poursuivent : licence de mécanique, licence pro, prépa ATS ou école d'ingénieurs.",
    mpc: "Pour qui aime imaginer des objets et la mécanique plus que l'atelier : les maths et la mécanique servent à dimensionner. Le bac général est cité par Onisep, mais les bacs STI2D ont déjà pratiqué la CAO : entraîne-toi avant (un logiciel de 3D gratuit suffit).",
    w: { MECA: 1, CREA: .3, MATH: .3 }, kw: ["design", "industrie", "auto"],
    p: { enc: 1, conc: .8, intense: .4, maths: .5, phys: .5, chim: 0, code: .2, ecrit: .1, oral: .2, vente: 0, bureau: .8, terrain: .1, indus: .5, ouvert: .5, gen: .4, integ: 0, sortie: 2 },
    src: { u: "https://www.onisep.fr/ressources/univers-formation/formations/post-bac/bts-conception-des-produits-industriels", l: "Fiche Onisep" } },

  { id: "bts_crsa", nom: "BTS CRSA (conception et réalisation de systèmes automatiques)", duree: "2 ans", sel: 1, selNote: "Accessible, mais pensé surtout pour les bacs STI2D et pro", cout: BTS_COST, alt: .6, inge: .5,
    alias: ["CRSA", "BTS CRSA"],
    core: ["robot", "industrie"],
    desc: "Concevoir puis construire des machines automatisées (lignes de production, robots, convoyeurs) : mécanique, automatismes, électricité, programmation d'automates, du plan 3D jusqu'au montage et à la mise en service. La conception occupe l'essentiel de l'horaire, le projet prend de la place en 2e année, et 6 semaines de stage concluent la 1re année.",
    apres: "Technicien en automatisme, en conception de machines ou en maintenance industrielle (automobile, agroalimentaire, pharmacie, énergie, robotique). Environ la moitié des diplômés poursuivent : licence pro, prépa ATS, école d'ingénieurs.",
    mpc: "Le plus « machines et mécanique » des BTS d'automatisme : le CIRA régule des procédés (fluides, chimie), l'électrotechnique gère l'énergie électrique, le CRSA fabrique les machines. Onisep ne cite pas le bac général : candidature possible, à appuyer par un vrai goût du concret (robotique, projet, stage).",
    w: { MECA: 1, ENER: .6, NUM: .3 }, kw: ["robot", "industrie", "auto"],
    p: { enc: 1, conc: 1, intense: .4, maths: .4, phys: .5, chim: 0, code: .4, ecrit: .1, oral: .2, vente: 0, bureau: .4, terrain: .2, indus: 1, ouvert: .4, gen: .3, integ: 0, sortie: 2 },
    src: { u: "https://www.onisep.fr/ressources/univers-formation/formations/post-bac/bts-conception-et-realisation-de-systemes-automatiques", l: "Fiche Onisep" } },

  { id: "bts_aero", nom: "BTS Aéronautique", duree: "2 ans", sel: 2, selNote: "Demandé ; environ un tiers des admis ont un bac général", cout: BTS_COST, alt: .5, inge: .5,
    alias: ["BTS aéronautique", "BTS aéro"],
    core: ["aero"],
    desc: "Fabriquer, assembler, contrôler et entretenir des avions, des hélicoptères et leurs équipements : aérodynamique, mécanique des fluides, propulsion, avionique, électricité, règles de navigabilité. Les métiers visés vont de la production à la maintenance ; 8 à 12 semaines de stage.",
    apres: "Technicien en production, en essais, en méthodes, en bureau d'études ou en maintenance chez les constructeurs, les équipementiers et les ateliers de maintenance. Plus de la moitié des diplômés poursuivent : licence pro aéronautique, L3 sciences de l'ingénieur, prépa ATS ou école d'ingénieurs.",
    mpc: "Un des BTS industriels où les bacs généraux sont les plus nombreux, et où la physique (fluides, thermodynamique) sert vraiment. Va aux portes ouvertes et parle dans ton dossier de ce qui t'attire dans l'aéronautique (aéroclub, maquettes, stage).",
    w: { MECA: 1, PHYS: .4, ENER: .3 }, kw: ["aero", "industrie"],
    p: { enc: 1, conc: .9, intense: .5, maths: .4, phys: .6, chim: .1, code: .1, ecrit: .2, oral: .2, vente: 0, bureau: .3, terrain: .3, indus: .9, ouvert: .4, gen: .2, integ: 0, sortie: 2 },
    src: { u: "https://www.onisep.fr/ressources/univers-formation/formations/post-bac/bts-aeronautique", l: "Fiche Onisep" } },

  { id: "bts_mav", nom: "BTS Métiers de l'audiovisuel (5 options : son, image, montage et postproduction, ingénierie des équipements, production)", duree: "2 ans", sel: 3, selNote: "Très sélectif : 3 à 6 % de candidats retenus dans les lycées les plus demandés", cout: "Gratuit en lycée public ; plusieurs milliers d'euros par an dans le privé", alt: .2, side: true, inge: 0,
    alias: ["BTS audiovisuel", "BTS MAV", "métiers de l'audiovisuel"],
    core: ["sonimage"],
    desc: "Tu choisis ton option dès la candidature : métiers du son, de l'image, du montage et de la postproduction, techniques d'ingénierie et exploitation des équipements (installer et régler le matériel des studios), ou gestion de la production. Dans les options techniques, la physique (optique, acoustique, électronique) compte, avec beaucoup de pratique.",
    apres: "Assistant son, preneur de son, cadreur, monteur, technicien d'exploitation ou assistant de production (télé, cinéma, spectacle, radio), souvent en contrats courts. Poursuite possible en licence pro, en licence cinéma ou en école spécialisée (ENS Louis-Lumière, Ensatt).",
    mpc: "Les options son, image et ingénierie des équipements sont celles où ta physique compte le plus. Plus de la moitié des admis ont un bac général, mais tout se joue sur la motivation : montre tes réalisations (vidéos, musique, son pour un groupe ou une asso).",
    w: { CREA: 1, PHYS: .4, NUM: .3, ENER: .2 }, kw: ["sonimage", "electronique"],
    p: { enc: 1, conc: 1, intense: .6, maths: .2, phys: .5, chim: 0, code: .2, ecrit: .2, oral: .4, vente: 0, bureau: .4, terrain: .5, indus: .5, ouvert: .3, gen: .2, integ: 0, sortie: 2 },
    src: { u: "https://www.onisep.fr/ressources/univers-formation/formations/post-bac/bts-metiers-de-l-audiovisuel-option-metiers-du-son", l: "Fiche Onisep" } },

  { id: "bts_opticien", nom: "BTS Opticien-lunetier", duree: "2 ans", sel: 2, selNote: "Variable : peu de places en lycée public, beaucoup d'écoles privées", cout: "Gratuit en lycée public ou en apprentissage ; plusieurs milliers d'euros par an en école privée", alt: .7, side: true, inge: 0,
    alias: ["opticien", "opticien-lunetier", "BTS opticien"],
    core: ["sante", "biomed"],
    desc: "Optique géométrique et physique, analyse de la vision (anatomie de l'œil, examen de vue), montage et réglage des lunettes en atelier, adaptation au client, plus de la gestion et de la vente. C'est le diplôme de référence pour devenir opticien ; son programme a été rénové (examen nouvelle version depuis 2026).",
    apres: "Opticien salarié en magasin, le plus souvent dans les grandes enseignes, puis responsable de magasin ou opticien indépendant. Beaucoup poursuivent un an de plus, par exemple en licence pro métiers de l'optique (sur dossier).",
    mpc: "L'optique de ton programme de physique sert directement, les maths aussi pour les calculs de verres. Mais c'est un métier de santé et de commerce : il faut aimer le contact avec les clients.",
    w: { VIE: 1, PHYS: .6, HUM: .5 }, kw: ["sante", "biomed", "entreprise"],
    p: { enc: 1, conc: .9, intense: .4, maths: .4, phys: .6, chim: 0, code: 0, ecrit: .1, oral: .6, vente: .6, bureau: .2, terrain: .6, indus: .4, ouvert: .3, gen: .2, integ: 0, sortie: 2 },
    src: { u: "https://www.onisep.fr/ressources/univers-formation/formations/post-bac/bts-opticien-lunetier", l: "Fiche Onisep" } },

  { id: "bts_geometre", nom: "BTS MGTMN (métiers du géomètre-topographe et de la modélisation numérique)", duree: "2 ans", sel: 1, cout: BTS_COST, alt: .6, side: true, inge: .5,
    alias: ["géomètre", "topographe", "BTS géomètre", "MGTMN"],
    core: ["construction", "environnement"],
    desc: "Mesurer le terrain, les bâtiments et les réseaux avec des instruments de précision, traiter les données, puis produire plans, cartes (SIG, systèmes d'information géographique) et maquettes numériques 3D (BIM). S'y ajoutent droit foncier, urbanisme et une bonne dose de maths appliquées à la mesure.",
    apres: "Technicien géomètre-topographe en cabinet de géomètre-expert, en bureau d'études, dans le BTP, à la SNCF, chez EDF ou dans les collectivités. Poursuite possible en licence pro, en prépa ATS génie civil ou en école d'ingénieurs (ESGT, ESTP, INSA Strasbourg).",
    mpc: "Un BTS méconnu qui fait travailler la géométrie, la trigonométrie et la physique de la mesure, avec une bonne part de terrain en plein air. Onisep cite le bac général parmi les bacs conseillés.",
    w: { BAT: 1, MATH: .6, NUM: .3 }, kw: ["construction", "environnement"],
    p: { enc: 1, conc: .9, intense: .4, maths: .6, phys: .3, chim: 0, code: .2, ecrit: .2, oral: .2, vente: 0, bureau: .5, terrain: .7, indus: .3, ouvert: .4, gen: .3, integ: 0, sortie: 2 },
    src: { u: "https://www.onisep.fr/ressources/univers-formation/formations/post-bac/bts-metiers-du-geometre-topographe-et-de-la-modelisation-numerique", l: "Fiche Onisep" } },

  { id: "bts_btp", nom: "BTS Bâtiment ou BTS Travaux publics", duree: "2 ans", sel: 1, cout: BTS_COST, alt: .7, inge: .5,
    alias: ["BTS bâtiment", "BTS travaux publics", "BTS TP"],
    core: ["construction"],
    desc: "Bâtiment : étudier, chiffrer et organiser la construction (sciences de la construction, économie, maquette numérique BIM, préparation de chantier). Travaux publics : routes, terrassements, réseaux, ouvrages, implantation et contrôle des travaux. Dans les deux cas, un stage de plusieurs semaines en entreprise, sur chantier ou en bureau d'études.",
    apres: "Chef de chantier, assistant conducteur de travaux, technicien de bureau d'études ou d'économie de la construction, dans les entreprises du BTP, l'ingénierie ou les collectivités. Poursuite possible en licence pro, en prépa ATS ou en école d'ingénieurs (INSA, CESI…).",
    mpc: "Les maths et la mécanique servent ici à du très concret (structures, métrés, devis). Onisep présente le BTS Bâtiment comme recrutant en majorité des bacs STI2D et pro, alors que le BTS Travaux publics cite aussi le bac général : un stage ou un job d'été sur un chantier pèse dans le dossier.",
    w: { BAT: 1, MECA: .3, MATH: .3 }, kw: ["construction"],
    p: { enc: 1, conc: .9, intense: .4, maths: .4, phys: .4, chim: .1, code: .1, ecrit: .2, oral: .3, vente: .1, bureau: .4, terrain: .8, indus: .8, ouvert: .4, gen: .3, integ: 0, sortie: 2 },
    src: { u: "https://www.onisep.fr/ressources/univers-formation/formations/post-bac/bts-travaux-publics", l: "Fiche Onisep" } },

  { id: "bts_chimie", nom: "BTS Métiers de la chimie", duree: "2 ans", sel: 1, cout: BTS_COST, alt: .5, inge: .5,
    alias: ["BTS chimie", "BTS métiers de la chimie"],
    core: ["chimie"],
    desc: "Technicien de laboratoire en chimie : synthèse, analyse et formulation (mise au point de produits), mesures en laboratoire ou sur les procédés de fabrication, avec des appareils comme les chromatographes et les spectrophotomètres. Beaucoup de travaux pratiques, et 8 semaines de stage.",
    apres: "Technicien chimiste ou de contrôle dans la chimie, la pharmacie, la cosmétique, la parfumerie, l'agroalimentaire ou le traitement des eaux. Poursuite possible en licence de chimie, en licence pro ou en prépa ATS pour viser une école d'ingénieurs.",
    mpc: "La suite logique si la chimie est ta partie préférée de physique-chimie et que tu aimes manipuler ; Onisep cite le bac général en premier. Compare avec le BUT Chimie, en 3 ans, qui mène directement à bac + 3.",
    w: { CHIM: 1, PHYS: .4, VIE: .2 }, kw: ["chimie", "industrie", "environnement"],
    p: { enc: 1, conc: .9, intense: .4, maths: .3, phys: .4, chim: 1, code: .1, ecrit: .2, oral: .2, vente: 0, bureau: .2, terrain: .1, indus: .9, ouvert: .4, gen: .3, integ: 0, sortie: 2 },
    src: { u: "https://www.onisep.fr/ressources/univers-formation/formations/post-bac/bts-metiers-de-la-chimie", l: "Fiche Onisep" } },

  { id: "bts_envnuc", nom: "BTS Environnement nucléaire", duree: "2 ans", sel: 1, cout: BTS_COST, alt: .5, side: true, inge: .5,
    alias: ["BTS environnement nucléaire", "environnement nucléaire", "radioprotection"],
    core: ["energie"],
    desc: "Travailler dans les installations nucléaires : radioprotection (protéger les personnes des rayonnements), sûreté, logistique des chantiers, maintenance et assainissement, gestion des déchets, démantèlement. La réglementation et la sécurité pèsent lourd ; deux stages de 4 semaines.",
    apres: "Technicien en radioprotection, en logistique nucléaire ou en démantèlement, chez les exploitants, l'ingénierie, la recherche ou les industries qui utilisent des sources radioactives ; près d'un diplômé sur deux de la voie scolaire travaille six mois après. Poursuite possible en licence pro radioprotection ou en école d'ingénieurs.",
    mpc: "La radioactivité vue en physique-chimie devient ici très concrète. Peu connu, ce BTS cite le bac général parmi ses accès ; il demande de la rigueur et d'accepter des règles de sécurité strictes.",
    w: { ENER: 1, PHYS: .6, VIE: .2 }, kw: ["energie", "industrie"],
    p: { enc: 1, conc: .9, intense: .4, maths: .3, phys: .6, chim: .3, code: .1, ecrit: .3, oral: .2, vente: 0, bureau: .3, terrain: .6, indus: 1, ouvert: .3, gen: .2, integ: 0, sortie: 2 },
    src: { u: "https://www.onisep.fr/ressources/univers-formation/formations/post-bac/bts-environnement-nucleaire", l: "Fiche Onisep" } },

  { id: "bts_fed", nom: "BTS FED (fluides, énergies, domotique)", duree: "2 ans", sel: 1, cout: BTS_COST, alt: .7, side: true, inge: .5,
    alias: ["BTS FED", "fluides énergies domotique", "domotique"],
    core: ["energie", "construction", "environnement"],
    desc: "Trois options : génie climatique et fluidique (chauffage, ventilation, eau), froid et conditionnement d'air, ou domotique et bâtiments communicants. Thermique, hydraulique, électrotechnique et régulation pour concevoir, mettre en service et entretenir des installations, en gérant au mieux l'énergie.",
    apres: "Technicien thermicien, chargé d'affaires, technicien de maintenance ou conseiller énergie, en bureau d'études, chez les installateurs, les fabricants, les producteurs d'énergie ou les collectivités. Poursuite possible en licence pro (énergétique, domotique) ou en école d'ingénieurs après une prépa ATS.",
    mpc: "La thermodynamique et l'électricité de physique-chimie servent directement, au service de l'efficacité énergétique des bâtiments. Le bac général est cité parmi les accès ; choisis l'option selon ce qui te plaît le plus (thermique, froid ou domotique).",
    w: { ENER: 1, BAT: .6, PHYS: .4 }, kw: ["energie", "construction", "environnement", "electronique"],
    p: { enc: 1, conc: .9, intense: .4, maths: .4, phys: .6, chim: .1, code: .2, ecrit: .2, oral: .3, vente: .2, bureau: .4, terrain: .6, indus: .7, ouvert: .4, gen: .3, integ: 0, sortie: 2 },
    src: { u: "https://www.onisep.fr/ressources/univers-formation/formations/post-bac/bts-fluides-energies-domotique-option-a-genie-climatique-et-fluidique", l: "Fiche Onisep" } }
]);
