// Santé et création. Vérifié le 5 octobre 2026 (voir dev/facts_fac_sante_crea.md).
add("sante", [
  { id: "sante_1a", nom: "Études de santé (nouvelle 1re année, fin du PASS et de la LAS)", duree: "1 ou 2 ans pour tenter la filière santé", sel: 3, cout: FAC_COST, alt: 0, inge: 0, conseil: ["svt"],
    core: ["sante"],
    alias: ["médecine", "PASS", "LAS", "pharmacie", "dentaire", "sage-femme", "maïeutique", "MMOPK", "médecin"],
    desc: "Annoncée pour la rentrée 2027, une voie unique remplace le PASS (parcours accès spécifique santé) et la LAS (licence accès santé) : une 1re année en trois blocs (santé, disciplinaire avec la licence de ton choix, transversal). Tu peux candidater à médecine, pharmacie, dentaire, sage-femme ou kiné à la fin de la 1re année, puis de la 2e.",
    apres: "Les métiers de santé (médecin, pharmacien, dentiste, sage-femme, kiné) ; sinon tu continues dans la licence de ton bloc disciplinaire, avec un seul redoublement possible. Les modalités précises restent à confirmer : suis les annonces de Parcoursup.",
    mpc: "Les maths et la physique-chimie aident (biophysique, chimie), mais l'ancien PASS faisait une grande place à la biologie : sans SVT, prévois un rattrapage. Le bloc disciplinaire doit être validé (10/20 minimum) comme le bloc santé : choisis une licence où tu es à l'aise.",
    w: { VIE: 1, HUM: .8, CHIM: .3 }, kw: ["sante", "biomed"],
    p: { enc: .4, conc: .2, intense: 1, maths: .3, phys: .4, chim: .5, code: 0, ecrit: .3, oral: .2, vente: 0, bureau: .6, terrain: 0, indus: 0, ouvert: .4, gen: .3, integ: 0, sortie: 6, concours: 1, fac: 1 },
    src: { u: "https://www.service-public.gouv.fr/particuliers/actualites/A18890", l: "Service-Public.fr" } },

  { id: "kine", nom: "Kinésithérapie (diplôme d'État de masseur-kinésithérapeute)", duree: "1 an d'université (parfois 2 ou 3), puis 4 ans en institut (IFMK)", sel: 3, cout: "Public : environ 180 à 255 €/an hors CVEC ; privé : de 1 200 € à plus de 10 000 €/an, environ 6 700 € en moyenne ; 77 % des étudiants sont en institut privé selon la FNEK (2026)", alt: 0, inge: 0, conseil: ["svt"],
    core: ["sante", "sport"],
    alias: ["kiné", "kinésithérapie", "kinésithérapeute", "IFMK"],
    desc: "Rééducation par le mouvement : anatomie, physiologie, biomécanique et beaucoup de stages. On entre en institut de formation en masso-kinésithérapie (IFMK) après une 1re année de santé, de STAPS ou de biologie, selon la convention entre l'université et l'institut. À partir de 2027, la kiné entre dans la nouvelle 1re année de santé.",
    apres: "Kinésithérapeute libéral ou salarié (hôpital, centre de rééducation, sport).",
    mpc: "La biomécanique fait appel à la physique, mais l'accès passe par une 1re année sélective où la biologie compte. L'avenir des voies STAPS et biologie reste à préciser avec la réforme : vérifie celles de chaque institut.",
    w: { HUM: 1, VIE: .8, PHYS: .2 }, kw: ["sante", "sport"],
    p: { enc: .6, conc: .9, intense: .8, maths: .2, phys: .3, chim: .2, code: 0, ecrit: .2, oral: .4, vente: 0, bureau: .2, terrain: .9, indus: 0, ouvert: .2, gen: .2, integ: 0, sortie: 5, concours: 1 },
    src: { u: "https://www.onisep.fr/ressources/univers-formation/formations/post-bac/diplome-d-etat-de-masseur-kinesitherapeute", l: "Fiche Onisep" } },

  { id: "manip_radio", nom: "Manipulateur en électroradiologie médicale (diplôme d'État ou DTS IMRT)", duree: "3 ans", sel: 2, selNote: "Très demandé : plus de 4 000 vœux pour 90 places au DTS du lycée Pierre-Gilles de Gennes à Paris en 2026", cout: "Diplôme d'État en institut public : environ 280 €/an (droits + CVEC) ; DTS en lycée public : gratuit ; DTS en lycée privé : environ 1 200 à 2 800 €/an", alt: .1, side: true, inge: 0,
    core: ["sante", "biomed"],
    alias: ["manip radio", "manipulateur radio", "imagerie médicale", "radiologie", "DTS IMRT"],
    desc: "Réaliser les examens d'imagerie (radio, scanner, IRM, médecine nucléaire) et les traitements de radiothérapie, au contact des patients et de machines de pointe. Deux voies : le diplôme d'État en institut, ou le DTS IMRT (diplôme de technicien supérieur en imagerie médicale et radiologie thérapeutique) en lycée.",
    apres: "Manipulateur à l'hôpital, en cabinet de radiologie ou en centre de radiothérapie, avec une très bonne insertion (100 % annoncé par certaines formations). Poursuite possible en licence pro (dosimétrie, radioprotection) ou en master d'imagerie et physique médicales.",
    mpc: "Un métier de santé où la physique (rayonnements, ondes, magnétisme) est très présente ; les formations attendent des bases en maths, en physique-chimie et en SVT. Candidate dans plusieurs formations : la demande est forte.",
    w: { VIE: .8, PHYS: .7, HUM: .7 }, kw: ["sante", "biomed"],
    p: { enc: .8, conc: .9, intense: .5, maths: .3, phys: .6, chim: .1, code: .1, ecrit: .2, oral: .4, vente: 0, bureau: .2, terrain: .7, indus: .3, ouvert: .2, gen: .2, integ: 0, sortie: 3 },
    src: { u: "https://www.onisep.fr/ressources/univers-formation/formations/post-bac/diplome-d-etat-de-manipulateur-d-electroradiologie-medicale", l: "Fiche Onisep" } },

  { id: "audio", nom: "Audioprothésiste (diplôme d'État)", duree: "3 ans", sel: 3, selNote: "Peu de places (quelques dizaines par centre), très sélectif", cout: "Environ 470 à 490 €/an de droits selon les centres, CVEC éventuellement en plus ; frais de sélection d'environ 80 € dans certains centres", alt: .2, side: true, inge: 0,
    core: ["sante", "biomed", "sonimage"],
    alias: ["audioprothésiste", "audioprothèse", "audioprothésistes"],
    desc: "Choisir, adapter et régler des aides auditives : acoustique, électronique, anatomie de l'oreille, et beaucoup de relation avec les patients. Une douzaine d'établissements en France, avec quelques dizaines de places chacun (de 30 à 52 d'après les chiffres publiés) ; admission sur Parcoursup, sur dossier, parfois avec entretien.",
    apres: "Audioprothésiste en centre d'audition, salarié ou à son compte (le diplôme d'État est obligatoire pour exercer) ; cadre de santé possible après 4 ans d'exercice.",
    mpc: "L'acoustique et l'électronique y sont centrales : un des métiers de santé les plus « physiques ». Les centres attendent aussi des bases en sciences de la vie : soigne ton dossier dans cette matière même sans la spécialité SVT.",
    w: { VIE: .8, PHYS: .7, HUM: .7, ENER: .3 }, kw: ["sante", "biomed", "sonimage"],
    p: { enc: .7, conc: .8, intense: .6, maths: .3, phys: .7, chim: .1, code: .1, ecrit: .2, oral: .5, vente: .3, bureau: .4, terrain: .5, indus: 0, ouvert: .2, gen: .2, integ: 0, sortie: 3 },
    src: { u: "https://www.onisep.fr/ressources/univers-formation/formations/post-bac/diplome-d-etat-d-audioprothesiste", l: "Fiche Onisep" } },

  { id: "veto", nom: "Études vétérinaires après le bac (concours commun des 4 écoles nationales vétérinaires)", duree: "6 ans", sel: 3, selNote: "Très sélectif : 280 places pour 3 815 candidatures en 2026 ; dossier sur Parcoursup, puis 4 oraux et 3 QCM courts en avril", cout: "École publique : frais de scolarité indiqués sur le site de chaque école", alt: 0, side: true, inge: 0, conseil: ["svt"],
    core: ["sante", "agro"],
    alias: ["vétérinaire", "véto", "école vétérinaire", "concours véto", "Alfort", "VetAgro Sup", "Oniris", "ENVT"],
    desc: "Depuis 2021, les quatre écoles nationales vétérinaires (Alfort, VetAgro Sup à Lyon, Oniris à Nantes, Toulouse) recrutent aussi dès le bac, par un concours commun sur Parcoursup : 70 places par école, pour un cursus de 6 ans qui mène au diplôme de vétérinaire.",
    apres: "Vétérinaire en clinique (animaux de compagnie, élevage, chevaux), en santé publique, en recherche ou dans l'industrie pharmaceutique et agroalimentaire.",
    mpc: "Aucune spécialité n'est exigée et une bonne part des candidats retenus en 2026 avaient maths + physique-chimie, mais les écoles recommandent la SVT (ou biologie-écologie) avec la physique-chimie : sans elle, il faudra combler la biologie par toi-même.",
    w: { VIE: 1, HUM: .6, CHIM: .3 }, kw: ["sante", "agro"],
    p: { enc: .7, conc: .8, intense: .9, maths: .3, phys: .3, chim: .5, code: 0, ecrit: .3, oral: .5, vente: 0, bureau: .3, terrain: .8, indus: 0, ouvert: .2, gen: .3, integ: 1, sortie: 6, concours: 1 },
    src: { u: "https://www.concours-veto-postbac.fr/", l: "Concours vétérinaire post-bac" } },

  { id: "ifsi", nom: "Soins infirmiers (institut de formation en soins infirmiers, IFSI)", duree: "3 ans", sel: 2, cout: "De 0 à environ 280 €/an selon l'institut et la région (droits + CVEC) ; certains instituts privés : environ 1 000 €/an", alt: .2, inge: 0,
    core: ["sante"],
    alias: ["infirmier", "infirmière", "IFSI", "soins infirmiers"],
    desc: "Formation d'infirmier (grade de licence) : la moitié du temps en cours (biologie, pharmacologie, soins), l'autre en stage à l'hôpital ou en libéral. Admission sur dossier via Parcoursup.",
    apres: "Infirmier, puis spécialisations : puéricultrice (1 an), bloc opératoire (18 mois), anesthésie (après 2 ans d'exercice), pratique avancée.",
    mpc: "Ta rigueur scientifique sert (calculs de doses, pharmacologie), mais c'est d'abord un métier de soin et de relation.",
    w: { HUM: 1, VIE: .8 }, kw: ["sante"],
    p: { enc: .9, conc: 1, intense: .8, maths: .3, phys: .1, chim: .2, code: 0, ecrit: .3, oral: .4, vente: 0, bureau: 0, terrain: 1, indus: 0, ouvert: .2, gen: .2, integ: 0, sortie: 3 },
    src: { u: "https://www.onisep.fr/ressources/univers-formation/formations/post-bac/diplome-d-etat-d-infirmier", l: "Fiche Onisep" } }
]);

add("crea", [
  { id: "archi", nom: "Écoles nationales supérieures d'architecture (ENSA)", duree: "5 ans (+ 1 an pour exercer en ton nom)", sel: 3, selNote: "Très demandé : plus de 3 000 candidatures pour environ 135 places à l'ENSA Paris-Belleville (admission 2026)", cout: "Environ 400 à 550 €/an selon l'école (2025-2026), CVEC en plus selon les écoles", alt: 0, inge: 0,
    core: ["construction", "design"],
    alias: ["architecture", "architecte", "ENSA", "école d'archi"],
    desc: "Projet, dessin, histoire de l'art, urbanisme, construction et structures. Candidature sur Parcoursup : dossier scolaire et lettre de motivation, puis entretien pour les candidats retenus. Licence en 3 ans (diplôme d'études en architecture), master en 2 ans (diplôme d'État d'architecte).",
    apres: "Architecte, urbaniste, scénographe, design d'espace.",
    mpc: "Maths et physique servent (structures, lumière, thermique), mais le dessin, la culture et le projet comptent autant : prépare un dossier qui montre ta créativité.",
    w: { BAT: 1, CREA: .9, PHYS: .2 }, kw: ["construction", "design", "environnement"],
    p: { enc: .6, conc: .7, intense: .9, maths: .3, phys: .3, chim: 0, code: .2, ecrit: .4, oral: .5, vente: 0, bureau: .6, terrain: .3, indus: .2, ouvert: .4, gen: .4, integ: 1, sortie: 5, concours: .5 },
    src: { u: "https://www.onisep.fr/ressources/univers-formation/formations/post-bac/diplome-d-etudes-en-architecture-grade-de-licence", l: "Fiche Onisep" } },

  { id: "dnmade", nom: "DN MADE (diplôme national des métiers d'art et du design)", duree: "3 ans (grade de licence)", sel: 3, selNote: "Très variable selon la mention et l'établissement ; sélection sur dossier et projet personnel", cout: "Gratuit en lycée public (hors achats de matériel) ; payant dans les établissements privés", alt: 0, inge: 0,
    core: ["design", "sonimage"],
    alias: ["DN MADE", "DNMADE", "métiers d'art", "design graphique"],
    desc: "Un diplôme de 3 ans en 14 mentions : objet, espace, graphisme, numérique, matériaux, mode, animation, spectacle, évènement, livre… Surtout en lycée public, avec beaucoup d'ateliers et de projets ; l'offre varie selon les établissements.",
    apres: "Designer, graphiste, concepteur ; poursuite en DSAA (diplôme supérieur d'arts appliqués), en master ou en école de design.",
    mpc: "Les mentions objet, numérique ou matériaux parlent aux profils scientifiques. Sélection sur dossier et projets personnels : à envisager si tu crées déjà.",
    w: { CREA: 1, MECA: .2 }, kw: ["design", "sonimage"],
    p: { enc: .8, conc: .9, intense: .6, maths: .1, phys: .1, chim: 0, code: .2, ecrit: .3, oral: .4, vente: 0, bureau: .6, terrain: 0, indus: .4, ouvert: .3, gen: .4, integ: 0, sortie: 3 },
    src: { u: "https://www.onisep.fr/ressources/univers-formation/formations/post-bac/dn-made-mention-objet", l: "Fiche Onisep" } },

  { id: "design_indus", nom: "Écoles de design industriel et de produit (ENSCI-Les Ateliers, Strate, autres écoles privées…)", duree: "5 ans après le bac", sel: 3, selNote: "Quelques dizaines de places par école publique ; sélection sur dossier et épreuves", cout: "Public (ENSCI, ENSAD) : environ 450 €/an de droits, plus la CVEC ; privé : environ 10 000 à 13 000 €/an (10 400 € en 1re année chez Strate en 2026-2027)", alt: .2, side: true, inge: 0,
    core: ["design"],
    alias: ["design industriel", "designer", "design produit", "ENSCI", "Strate", "design automobile", "ENSAD", "Arts décoratifs"],
    desc: "Imaginer des objets, des véhicules ou des interfaces : dessin, maquettes, matériaux, ergonomie, projets pour des entreprises. L'ENSCI-Les Ateliers (école nationale supérieure de création industrielle, publique) recrute dès le bac, via Parcoursup puis concours, avec aussi une voie « Science et Design » pour les profils scientifiques.",
    apres: "Designer produit, designer automobile, designer d'interaction, en agence ou chez les industriels.",
    mpc: "Le pont entre ton goût pour la technique et la création. Prépare un dossier de travaux (dessin, maquettes, projets personnels) : c'est lui qui compte pour le concours ou le portfolio demandé.",
    w: { CREA: 1, MECA: .5 }, kw: ["design", "auto", "industrie"],
    p: { enc: .5, conc: .9, intense: .7, maths: .2, phys: .3, chim: .1, code: .2, ecrit: .3, oral: .5, vente: .1, bureau: .6, terrain: 0, indus: .5, ouvert: .3, gen: .3, integ: 1, sortie: 5, concours: 1 },
    src: { u: "https://www.onisep.fr/formation/les-principaux-domaines-de-formation/les-ecoles-d-art/les-ecoles-de-creation-et-de-design", l: "Onisep" } },

  { id: "son_image", nom: "Écoles du son et de l'image (ENS Louis-Lumière, licences cinéma, écoles privées…)", duree: "3 à 5 ans", sel: 3, cout: "Public : quelques centaines d'euros par an (environ 300 € de droits à l'ENS Louis-Lumière, plus la CVEC) ; privé : plusieurs milliers d'euros par an (8 500 € en 1re année à SAE Institute Paris en 2026-2027)", alt: .2, side: true, inge: 0,
    core: ["sonimage"],
    alias: ["Louis-Lumière", "ENS Louis-Lumière", "ingénieur du son", "ingé son", "cinéma", "école de cinéma", "audiovisuel", "BTS audiovisuel", "SAE Institute"],
    desc: "Prise de son, mixage, image, lumière, postproduction : des formations très techniques où l'acoustique, l'optique et l'électronique servent. L'ENS Louis-Lumière (école nationale supérieure, publique) recrute sur concours après 2 ans d'études supérieures ; les écoles privées recrutent dès le bac.",
    apres: "Ingénieur du son, chef opérateur, étalonneur, technicien lumière pour le cinéma, la musique, la télé ou le spectacle.",
    mpc: "Louis-Lumière exige 2 ans d'études supérieures avant le concours (BTS métiers de l'audiovisuel, licence…). Pour la spécialité son, les épreuves portent notamment sur les maths, la physique et l'électronique : ton profil est un vrai atout.",
    w: { CREA: 1, PHYS: .5, ENER: .4 }, kw: ["sonimage", "electronique"],
    p: { enc: .6, conc: .9, intense: .6, maths: .3, phys: .6, chim: 0, code: .3, ecrit: .3, oral: .4, vente: 0, bureau: .5, terrain: .5, indus: .4, ouvert: .3, gen: .3, integ: 0, sortie: 5, concours: 1 },
    src: { u: "https://www.onisep.fr/formation/les-principaux-domaines-de-formation/les-ecoles-d-audiovisuel", l: "Onisep" } }
]);
